export interface BlogArticle {
    slug: string;
    title: string;
    metaTitle: string;
    metaDescription: string;
    excerpt: string;
    date: string;
    readTime: string;
    category: string;
    tags: string[];
    content: Array<{
        type: 'h2' | 'h3' | 'p' | 'ul' | 'tip';
        text?: string;
        items?: string[];
    }>;
}

export const BLOG_ARTICLES: BlogArticle[] = [
    {
        slug: 'como-instalar-cable-red-casa',
        title: 'Cómo instalar cable de red en casa: guía completa',
        metaTitle: 'Cómo instalar cable de red en casa — Guía profesional 2024',
        metaDescription: 'Guía paso a paso para instalar cable de red Ethernet en tu hogar. Cat6 vs Cat6A, herramientas necesarias, coste y consejos profesionales.',
        excerpt: 'Todo lo que necesitas saber para cablear tu hogar con Ethernet: tipos de cable, herramientas, costes y cuándo llamar a un profesional.',
        date: '2024-12-15',
        readTime: '8 min',
        category: 'Guías',
        tags: ['red doméstica', 'ethernet', 'cat6', 'instalación'],
        content: [
            { type: 'h2', text: '¿Por qué instalar cable de red en casa?' },
            { type: 'p', text: 'El Wi-Fi es cómodo, pero el cable Ethernet ofrece velocidades más estables, menor latencia y mayor fiabilidad. Para gaming, streaming 4K, teletrabajo o domótica, un cableado estructurado marca la diferencia.' },
            { type: 'h2', text: 'Tipos de cable: Cat6 vs Cat6A vs Cat7' },
            { type: 'ul', items: [
                'Cat6 — hasta 1 Gbps a 100m. Ideal para la mayoría de hogares. Desde 95€/punto.',
                'Cat6A — hasta 10 Gbps a 100m. Recomendado para futuras necesidades. Desde 115€/punto.',
                'Cat7 — hasta 10 Gbps con blindaje extra. Máxima protección contra interferencias. Desde 140€/punto.',
            ]},
            { type: 'h2', text: '¿Qué incluye cada punto de red?' },
            { type: 'p', text: 'Un punto de red profesional incluye: cable Ethernet de la categoría elegida, keystone RJ45, placa de pared, canaleta o tubo corrugado si es necesario, y certificación con equipo Fluke.' },
            { type: 'h2', text: 'Tipos de instalación' },
            { type: 'ul', items: [
                'Superficial (canaleta) — 8€/m. Visible pero económica.',
                'Techo técnico — 6€/m. Se oculta en el falso techo.',
                'Empotrado existente — 12€/m. Usando conductos existentes.',
                'Empotrado nuevo — 18€/m. Abriendo nueva roza.',
            ]},
            { type: 'h2', text: '¿Cuánto cuesta instalar red en casa?' },
            { type: 'p', text: 'Un hogar típico con 6–8 puntos de red Cat6 cuesta entre 800€ y 1.200€ (IVA incluido). Puedes calcular tu presupuesto exacto con nuestra calculadora de instalación.' },
            { type: 'tip', text: '💡 Usa nuestra calculadora gratuita para obtener un presupuesto detallado en segundos.' },
            { type: 'h2', text: '¿Puedo hacerlo yo mismo?' },
            { type: 'p', text: 'Si tienes experiencia en bricolaje puedes colocar canaletas o pasar cables. Pero para la terminación (crimpado RJ45, patch panel, certificación), recomendamos un profesional. Un punto mal terminado puede causar pérdida de velocidad y desconexiones.' },
            { type: 'h2', text: '¿Cuándo llamar a un profesional?' },
            { type: 'ul', items: [
                'Más de 4 puntos de red',
                'Instalación empotrada',
                'Necesitas rack y patch panel',
                'Quieres certificación Fluke',
                'Necesitas VLANs o red segmentada',
            ]},
        ],
    },
    {
        slug: 'cat6-vs-cat6a-vs-cat7-diferencias',
        title: 'Cat6 vs Cat6A vs Cat7: ¿cuál elegir?',
        metaTitle: 'Cat6 vs Cat6A vs Cat7 — Diferencias, precios y recomendaciones',
        metaDescription: 'Comparativa completa entre cables Cat6, Cat6A y Cat7. Velocidades, precios, usos recomendados y cuál elegir para tu instalación de red.',
        excerpt: 'Comparativa detallada entre los tres cables Ethernet más populares: velocidad, precio, blindaje y para qué sirve cada uno.',
        date: '2024-11-20',
        readTime: '6 min',
        category: 'Comparativas',
        tags: ['cat6', 'cat6a', 'cat7', 'ethernet', 'comparativa'],
        content: [
            { type: 'h2', text: 'Tabla comparativa rápida' },
            { type: 'p', text: 'Cat6: 1 Gbps, hasta 250 MHz, sin blindaje estándar, 95€/punto. Cat6A: 10 Gbps, hasta 500 MHz, blindaje parcial, 115€/punto. Cat7: 10 Gbps, hasta 600 MHz, blindaje completo (S/FTP), 140€/punto.' },
            { type: 'h2', text: 'Cat6 — El estándar para hogares' },
            { type: 'p', text: 'Cat6 soporta velocidades de hasta 1 Gbps a 100 metros. Es suficiente para la mayoría de hogares y pequeñas oficinas. Streaming, videollamadas, gaming — todo funciona perfecto con Cat6.' },
            { type: 'h2', text: 'Cat6A — La inversión a futuro' },
            { type: 'p', text: 'Cat6A es la opción recomendada para quien quiere preparar su red para el futuro. Soporta 10 Gbps a 100 metros. Ideal para oficinas, estudios de diseño, y cualquier entorno que pueda necesitar más ancho de banda en los próximos años.' },
            { type: 'h2', text: 'Cat7 — Máxima protección' },
            { type: 'p', text: 'Cat7 incluye blindaje completo (S/FTP) en cada par y en el conjunto. Es la mejor opción para entornos con muchas interferencias electromagnéticas: naves industriales, hospitales, edificios con mucho cableado eléctrico.' },
            { type: 'h2', text: '¿Cuál elegir?' },
            { type: 'ul', items: [
                'Hogar: Cat6 (suficiente para 99% de necesidades)',
                'Oficina: Cat6A (preparado para 10 Gbps)',
                'Industrial/Clínica: Cat7 (máxima protección)',
                '¿No estás seguro? Consúltanos gratis — te asesoramos.',
            ]},
            { type: 'tip', text: '📞 Llámanos al +34 605 974 605 o usa nuestra calculadora de instalación para comparar precios.' },
        ],
    },
    {
        slug: 'como-mejorar-red-wifi-oficina',
        title: 'Cómo mejorar la red Wi-Fi en tu oficina',
        metaTitle: 'Mejorar Wi-Fi en oficina — 7 soluciones profesionales',
        metaDescription: 'Tu Wi-Fi de oficina es lento? Descubre 7 soluciones profesionales para mejorar la velocidad y cobertura de tu red inalámbrica.',
        excerpt: '¿Wi-Fi lento en la oficina? 7 soluciones probadas para mejorar velocidad, cobertura y estabilidad de tu red inalámbrica.',
        date: '2024-10-30',
        readTime: '7 min',
        category: 'Consejos',
        tags: ['wifi', 'oficina', 'rendimiento', 'access point'],
        content: [
            { type: 'h2', text: 'El problema: Wi-Fi lento y desconexiones' },
            { type: 'p', text: 'En una oficina con más de 10 dispositivos, el router del operador no da abasto. Interferencias, saturación de canales y mala ubicación son las causas más frecuentes de Wi-Fi lento en oficinas.' },
            { type: 'h2', text: '7 soluciones profesionales' },
            { type: 'h3', text: '1. Cableado Ethernet + Access Points' },
            { type: 'p', text: 'La solución más efectiva: instalar puntos de red Ethernet y conectar Access Points profesionales (no repetidores). Cada AP tiene su cable, con velocidad garantizada.' },
            { type: 'h3', text: '2. Separar redes (VLAN)' },
            { type: 'p', text: 'Crear redes separadas para empleados y visitantes. Así la red corporativa no se satura cuando hay visitas.' },
            { type: 'h3', text: '3. Usar la banda de 5 GHz' },
            { type: 'p', text: 'La banda de 5 GHz es menos congestionada y más rápida. Los AP profesionales gestionan automáticamente en qué banda se conecta cada dispositivo.' },
            { type: 'h3', text: '4. Ubicar APs correctamente' },
            { type: 'p', text: 'Un AP profesional cubre ~150m² en oficina. Planificar la ubicación es clave para evitar zonas muertas.' },
            { type: 'h3', text: '5. Switch gestionable' },
            { type: 'p', text: 'Un buen switch permite priorizar tráfico (QoS), crear VLANs y monitorizar la red. Instalar switch: 60€.' },
            { type: 'h3', text: '6. Cable Cat6A' },
            { type: 'p', text: 'Si tu cableado es antiguo (Cat5 o Cat5e), actualizarlo a Cat6A te da 10x más velocidad potencial.' },
            { type: 'h3', text: '7. Configuración profesional' },
            { type: 'p', text: 'Un técnico puede optimizar canales, potencia, bandas y seguridad. Configuración de red: 120€.' },
            { type: 'tip', text: '🔧 ¿Necesitas mejorar tu Wi-Fi? Solicita una consulta gratuita — te visitamos y asesoramos sin compromiso.' },
        ],
    },
    {
        slug: 'que-es-cableado-estructurado',
        title: 'Qué es el cableado estructurado y por qué lo necesitas',
        metaTitle: 'Qué es cableado estructurado — Guía completa para empresas',
        metaDescription: 'Qué es el cableado estructurado, cómo funciona, qué ventajas tiene y por qué tu empresa necesita una red profesional certificada.',
        excerpt: 'El cableado estructurado es la base de toda infraestructura de red moderna. Descubre qué es, cómo funciona y por qué lo necesitas.',
        date: '2024-09-15',
        readTime: '6 min',
        category: 'Educación',
        tags: ['cableado estructurado', 'red profesional', 'infraestructura'],
        content: [
            { type: 'h2', text: '¿Qué es el cableado estructurado?' },
            { type: 'p', text: 'Es un sistema de cableado de red estandarizado que conecta todos los dispositivos de un edificio (ordenadores, teléfonos, impresoras, cámaras) a través de una infraestructura organizada, certificada y fácil de mantener.' },
            { type: 'h2', text: 'Componentes del cableado estructurado' },
            { type: 'ul', items: [
                'Cable Ethernet (Cat6/Cat6A/Cat7)',
                'Patch panels para organización central',
                'Rack o armario de telecomunicaciones',
                'Keystones RJ45 y placas de pared',
                'Switchs y routers',
                'Canaletas y gestión de cables',
            ]},
            { type: 'h2', text: 'Ventajas del cableado estructurado' },
            { type: 'ul', items: [
                'Velocidad y estabilidad garantizadas',
                'Fácil de ampliar y modificar',
                'Cumple estándares internacionales (TIA/EIA-568)',
                'Reducción de costes de mantenimiento',
                'Certificable con Fluke para garantía',
            ]},
            { type: 'h2', text: '¿Cuándo necesitas cableado estructurado?' },
            { type: 'ul', items: [
                'Oficinas con más de 5 equipos',
                'Empresas en crecimiento',
                'Clínicas, hoteles, tiendas',
                'Edificios nuevos o reformas integrales',
            ]},
            { type: 'tip', text: '📋 Solicita tu presupuesto — diseñamos la red perfecta para tu negocio.' },
        ],
    },
    {
        slug: 'como-instalar-rack-de-red',
        title: 'Cómo instalar un rack de red: guía para empresas',
        metaTitle: 'Cómo instalar rack de red — Tipos, tamaños y precios',
        metaDescription: 'Guía completa para instalar un rack de red en tu empresa. Tipos de rack, tamaños, componentes necesarios y precios de instalación.',
        excerpt: 'Guía completa para elegir e instalar el rack de red perfecto para tu empresa: tipos, tamaños, componentes y coste.',
        date: '2024-08-20',
        readTime: '7 min',
        category: 'Guías',
        tags: ['rack', 'patch panel', 'servidor', 'instalación'],
        content: [
            { type: 'h2', text: '¿Qué es un rack de red?' },
            { type: 'p', text: 'Un rack de red (o armario de telecomunicaciones) es el centro neurálgico de tu red. Aquí se conectan todos los cables y se alojan los equipos de red: switches, routers, patch panels y organizadores.' },
            { type: 'h2', text: 'Tipos de rack' },
            { type: 'h3', text: 'Rack mural (6U–12U)' },
            { type: 'p', text: 'Se fija a la pared. Ideal para pequeñas oficinas y tiendas. Ocupa poco espacio. Coste: desde 150€ (solo rack).' },
            { type: 'h3', text: 'Rack de suelo (22U–42U)' },
            { type: 'p', text: 'Para empresas medianas y grandes. Mayor capacidad, mejor ventilación. Coste: desde 350€ (solo rack).' },
            { type: 'h2', text: 'Componentes esenciales' },
            { type: 'ul', items: [
                'Patch panel (24 o 48 puertos)',
                'Switch gestionable',
                'Organizador de cables',
                'Bandeja para router/ONT',
                'Regleta de enchufes (PDU)',
                'Ventilación (ventiladores en techo)',
            ]},
            { type: 'h2', text: 'Precios de instalación de rack' },
            { type: 'ul', items: [
                'Rack mural básico (6U): ~250€',
                'Rack mural completo (12U): ~450€',
                'Rack suelo profesional (22U+): ~750€–1.200€',
                'Incluye: montaje, patch panel, organización cableado',
            ]},
            { type: 'tip', text: '🗄️ ¿Necesitas un rack? Usa nuestra calculadora para incluirlo en tu presupuesto.' },
        ],
    },
    {
        slug: 'errores-comunes-instalacion-red',
        title: '6 errores comunes en la instalación de red (y cómo evitarlos)',
        metaTitle: 'Errores comunes instalación de red — Cómo evitarlos',
        metaDescription: '6 errores frecuentes que cometen los no profesionales al instalar red Ethernet. Aprende a evitarlos y cuándo llegar a un instalador profesional.',
        excerpt: 'Errores que cuestan dinero: 6 fallos frecuentes en instalaciones de red domésticas y de oficina, y cómo evitarlos.',
        date: '2024-07-10',
        readTime: '5 min',
        category: 'Consejos',
        tags: ['errores', 'instalación', 'consejos', 'profesional'],
        content: [
            { type: 'h2', text: '1. Usar cable de baja calidad' },
            { type: 'p', text: 'Cables baratos sin certificación pueden no cumplir las especificaciones Cat6. Resultado: velocidad inferior a lo esperado, errores y desconexiones. Siempre usa cable certificado de marca reconocida.' },
            { type: 'h2', text: '2. No respetar el radio de curvatura' },
            { type: 'p', text: 'El cable Ethernet no debe doblarse más de 4 veces su diámetro. Dobleces excesivos dañan los pares internos y reducen el rendimiento. Usa curvas suaves en canaletas y esquinas.' },
            { type: 'h2', text: '3. Mezclar categorías de cable' },
            { type: 'p', text: 'Si instalas Cat6A pero usas un patch cord Cat5e, tu velocidad se limita al componente más lento. Mantén la misma categoría en toda la cadena: cable, keystone, patch panel y patch cord.' },
            { type: 'h2', text: '4. No certificar los puntos' },
            { type: 'p', text: 'Sin certificación, no puedes saber si un punto funciona al 100%. Un certificador Fluke detecta errores que un simple test de continuidad no ve. Insiste en certificación profesional.' },
            { type: 'h2', text: '5. Cables junto a líneas eléctricas' },
            { type: 'p', text: 'El cable Ethernet sufre interferencias si pasa junto a cables eléctricos. Mantén al menos 20cm de separación o usa cable blindado (Cat7) en casos necesarios.' },
            { type: 'h2', text: '6. No planificar la escalabilidad' },
            { type: 'p', text: 'Instala siempre más puntos de los que necesitas hoy. Añadir puntos después es mucho más caro que incluirlos en la instalación inicial.' },
            { type: 'tip', text: '✅ Evita estos errores: confía en un instalador profesional certificado. Solicita tu presupuesto gratis.' },
        ],
    },
];
