import { SEOPageConfig } from "./types";

export const SEO_PAGES_EN: SEOPageConfig[] = [
    {
        slug: 'instalacion-cable-red-barcelona',
        title: 'Network Cable Installation Barcelona | CableCore',
        h1: 'Professional network cable installation in Barcelona',
        h2s: ['Why choose CableCore?', 'Installation process', 'Frequently asked questions'],
        intro: 'Professional Ethernet network cable installation service in Barcelona and surrounding areas. Cat5e, Cat6, Cat6A, and Cat7 cabling for homes, offices, and industrial warehouses.',
        metaDescription: 'Network cable installation in Barcelona. Professional Cat5e, Cat6, Cat6A, Cat7 Ethernet cabling. Free quote. ☎ +34 605 974 605',
        cta: 'Need to install network cable in Barcelona?',
        features: [
            { icon: '🔌', title: 'All categories', text: 'We install Cat5e, Cat6, Cat6A, and Cat7 according to your speed and budget needs.' },
            { icon: '🏠', title: 'Homes and offices', text: 'Network cabling solutions tailored for residential and business spaces.' },
            { icon: '📋', title: 'Free quote', text: 'On-site technical visit and detailed quote with no obligation.' },
            { icon: '⚡', title: 'Fast installation', text: 'We install your network in the shortest possible time with minimal disruption.' },
            { icon: '✅', title: 'Testing', text: 'All installations are tested to guarantee performance.' },
            { icon: '🛡️', title: 'Warranty', text: 'Warranty on workmanship and materials for your peace of mind.' },
        ],
        faq: [
            { q: 'How much does it cost to install network cable in Barcelona?', a: 'The price depends on the cable type, length in meters, and installation complexity. An installed Cat6 network point starts from €45. Ask for a free quote.' },
            { q: 'How long does the installation take?', a: 'A domestic installation of 4-8 points is done in 1 day. Enterprise projects can take 2-5 days.' },
            { q: 'What cable category do I need?', a: 'For domestic use, Cat6 is sufficient. For offices, we recommend Cat6A. For industrial or high-speed setups, Cat7.' },
        ],
    },
    {
        slug: 'cableado-estructurado-barcelona',
        title: 'Structured Cabling Barcelona | CableCore',
        h1: 'Professional structured cabling in Barcelona',
        h2s: ['Advantages of structured cabling', 'Our process', 'Frequently asked questions'],
        intro: 'Design and installation of structured cabling for companies in Barcelona. Organized, scalable, and tested network for offices, retail stores, and industrial warehouses.',
        metaDescription: 'Structured cabling in Barcelona. Design, installation, and testing of corporate networks. Free quote. ☎ +34 605 974 605',
        cta: 'Do you need structured cabling in Barcelona?',
        features: [
            { icon: '🏗️', title: 'Custom design', text: 'We design the network infrastructure tailored to your space and requirements.' },
            { icon: '📐', title: 'Current standards', text: 'We comply with ISO/IEC 11801 and ANSI/TIA-568 standards.' },
            { icon: '📈', title: 'Scalability', text: 'A network ready to grow with your business without needing to redo the installation.' },
            { icon: '🔧', title: 'Maintenance', text: 'Easy identification and management of endpoint ports thanks to professional labeling.' },
            { icon: '🏭', title: 'All sectors', text: 'Offices, retail, hotels, clinics, industrial warehouses, and more.' },
            { icon: '📊', title: 'Professional Testing', text: 'Testing of every point with professional equipment.' },
        ],
        faq: [
            { q: 'What is structured cabling?', a: 'It is an organized and standardized cabling system that allows efficient management of voice, data, and video networks within a building.' },
            { q: 'How much does structured cabling cost?', a: 'It depends on the number of points and complexity. A rough estimate for a 20-point office is between €2,000 and €4,000.' },
            { q: 'Can it be installed in an already built venue?', a: 'Yes, we work with conduits, dropped ceilings, and embedded walls to adapt the installation to any existing space.' },
        ],
    },
    {
        slug: 'instalacion-cat6-barcelona',
        title: 'Cat6 Installation Barcelona | CableCore',
        h1: 'Cat6 cable installation in Barcelona',
        h2s: ['Advantages of Cat6', 'Installation process', 'Frequently asked questions'],
        intro: 'Professional Cat6 network cabling installation in Barcelona. Speeds up to 1 Gbps, ideal for homes and offices. Free, no-obligation quote.',
        metaDescription: 'Cat6 Installation in Barcelona. 1Gbps Ethernet cable for home and office. Professional installer. Free quote. ☎ +34 605 974 605',
        cta: 'Need Cat6 in Barcelona?',
        features: [
            { icon: '⚡', title: 'Up to 1 Gbps', text: 'More than enough speed for browsing, 4K streaming, and remote work.' },
            { icon: '💰', title: 'Best value for money', text: 'Cat6 cable at the best price with professional installation included.' },
            { icon: '🏠', title: 'Ideal for homes', text: 'Perfect for households seeking a stable, fast connection.' },
            { icon: '📡', title: 'WiFi 6 compatible', text: 'The perfect foundation for WiFi 6 routers and access points.' },
            { icon: '🔌', title: 'Tested RJ45', text: 'All points tested by our skilled technicians.' },
            { icon: '🛠️', title: 'Clean installation', text: 'Conduits, dropped ceilings, or embedded tracking depending on your preference.' },
        ],
        faq: [
            { q: 'What is the difference between Cat5e and Cat6?', a: 'Cat6 supports speeds up to 1 Gbps over 100 meters, while Cat5e supports up to 100 Mbps, with better shielding against interference.' },
            { q: 'Is Cat6 sufficient for my office?', a: 'For small offices with up to 10 employees, Cat6 is an excellent choice. If you need more than 1 Gbps, consider Cat6A.' },
        ],
    },
    {
        slug: 'instalacion-cat6a-barcelona',
        title: 'Cat6A Installation Barcelona | CableCore',
        h1: 'Cat6A cable installation in Barcelona',
        h2s: ['Advantages of Cat6A', 'Installation process', 'Frequently asked questions'],
        intro: 'Professional Cat6A network cabling installation in Barcelona. 10 Gbps speeds, shielded, ideal for companies demanding high-performance networking.',
        metaDescription: 'Cat6A installation in Barcelona. Shielded 10Gbps corporate Ethernet cable. Professional installer. ☎ +34 605 974 605',
        cta: 'Need Cat6A for your business?',
        features: [
            { icon: '🚀', title: 'Up to 10 Gbps', text: '10 times faster than standard Cat6 for massive data transfers.' },
            { icon: '🛡️', title: 'Shielded (FTP)', text: 'Greater protection against electromagnetic interference.' },
            { icon: '🏢', title: 'Ideal for enterprise', text: 'The preferred choice for medium and large offices.' },
            { icon: '📊', title: 'Future-proof', text: 'Ready for upcoming technologies like WiFi 6E, PoE++, and 10GbE.' },
            { icon: '🏥', title: 'Demanding sectors', text: 'Perfect for clinics, design studios, and tech companies.' },
            { icon: '✅', title: 'Testing', text: 'We test each endpoint up to 500 MHz with professional testers.' },
        ],
        faq: [
            { q: 'Is Cat6A worth it over Cat6?', a: 'If your company handles large volumes of data or you plan to grow in the next 5-10 years, Cat6A is a smart investment.' },
            { q: 'Will Cat6A work with my current devices?', a: 'Yes, Cat6A is backward compatible with Cat6 and Cat5e. You can upgrade without changing your standard switches or routers.' },
        ],
    },
    {
        slug: 'instalacion-cat7-barcelona',
        title: 'Cat7 Installation Barcelona | CableCore',
        h1: 'Cat7 cable installation in Barcelona',
        h2s: ['Advantages of Cat7', 'Installation process', 'Frequently asked questions'],
        intro: 'Cat7 cabling installation in Barcelona for the most demanding environments. S/FTP shielding, speeds up to 10 Gbps, and a frequency of 600 MHz.',
        metaDescription: 'Cat7 installation in Barcelona. S/FTP 10Gbps 600MHz cable for industrial environments and data centers. ☎ +34 605 974 605',
        cta: 'Do you need Cat7 for your project?',
        features: [
            { icon: '⚡', title: '10 Gbps / 600 MHz', text: 'Maximum performance for industrial environments and data centers.' },
            { icon: '🛡️', title: 'Double S/FTP shielding', text: 'Each pair individually shielded plus an overall outer shield.' },
            { icon: '🏭', title: 'Industrial', text: 'Ideal for factories, warehouses, and environments with high electromagnetic interference.' },
            { icon: '📡', title: 'PoE++', text: 'Supports Power over Ethernet for cameras, APs, and IoT devices.' },
            { icon: '🔒', title: 'Maximum reliability', text: 'GG45 or TERA connectors for foolproof, error-free connections.' },
            { icon: '📐', title: 'Full compliance', text: 'Meets the strictest standards: ISO/IEC 11801 Class F.' },
        ],
        faq: [
            { q: 'When do I need Cat7?', a: 'When the environment has significant electromagnetic interference (factories, server rooms) or you need maximum signal quality.' },
            { q: 'Is Cat7 compatible with my equipment?', a: 'Yes, Cat7 featuring RJ45 connectors is fully compatible with all standard networking hardware.' },
        ],
    },
    {
        slug: 'instalador-rj45-barcelona',
        title: 'RJ45 Installer Barcelona | CableCore',
        h1: 'RJ45 connector installer in Barcelona',
        h2s: ['Professional RJ45 service', 'Process', 'FAQ'],
        intro: 'RJ45 connector installation and testing in Barcelona. Professional crimping, faceplate installation, and thorough testing of every network endpoint.',
        metaDescription: 'RJ45 Installer in Barcelona. Professional crimping, network faceplates, and testing. Fast, guaranteed service. ☎ +34 605 974 605',
        cta: 'Looking for an RJ45 installer?',
        features: [
            { icon: '🔌', title: 'Professional crimping', text: 'RJ45 connector termination using precision tools.' },
            { icon: '🔍', title: 'Individual testing', text: 'Each connector is verified with a professional tester.' },
            { icon: '📐', title: 'Cat5e to Cat7', text: 'We work with all Ethernet cable categories.' },
            { icon: '🏠', title: 'Home and business', text: 'On-site service for homes, offices, and industrial units.' },
            { icon: '⚡', title: 'Fast service', text: 'Same-day RJ45 endpoint installation service in Barcelona.' },
            { icon: '✅', title: 'Warranty', text: 'Warranty included for every installed and tested point.' },
        ],
        faq: [
            { q: 'How much does it cost to install an RJ45 port?', a: 'An installed and tested RJ45 port ranges from €15 (connector only) to €45-85 (full point with cabling and faceplate).' },
        ],
    },
    {
        slug: 'instalacion-rack-red-barcelona',
        title: 'Network Rack Installation Barcelona | CableCore',
        h1: 'Network rack installation in Barcelona',
        h2s: ['Types of racks we install', 'Process', 'FAQ'],
        intro: 'Professional network rack installation in Barcelona. Wall-mounted racks, floor-standing units, and telecom cabinets complete with patch panels and neat cable management.',
        metaDescription: 'Network rack installation in Barcelona. Wall and floor racks, patch panels, robust cable management. ☎ +34 605 974 605',
        cta: 'Need to install a network rack?',
        features: [
            { icon: '🗄️', title: 'Wall rack', text: 'From 6U to 18U for offices and SMEs. Clean wall mounting.' },
            { icon: '🏗️', title: 'Floor rack', text: 'From 22U to 42U for major enterprise installations and data centers.' },
            { icon: '🔗', title: 'Patch panel', text: 'Connection structuring with Cat6/Cat6A/Cat7 patch panels.' },
            { icon: '🔄', title: 'Organization', text: 'Cable routing loops, blanking panels, and professional cable management.' },
            { icon: '🔌', title: 'Power supply', text: 'Rack-mount PDUs equipped with surge protection.' },
            { icon: '❄️', title: 'Ventilation', text: 'Fan trays and thermostats to keep closed racks cool.' },
        ],
        faq: [
            { q: 'What size rack do I need?', a: 'For a small office, a 12U wall rack is usually enough. For more than 20 points, we recommend a floor rack starting at 22U.' },
            { q: 'Is the patch panel included?', a: 'We offer rack installation with and without patch panels. The integrated rack + patch panel bundle includes complete cable organization.' },
        ],
    },
    {
        slug: 'instalacion-red-oficina-barcelona',
        title: 'Office Network Installation Barcelona | CableCore',
        h1: 'Office network installation in Barcelona',
        h2s: ['Office solutions', 'Process', 'FAQ'],
        intro: 'Complete network installation for offices in Barcelona. Network engineering, structured cabling, rack setups, enterprise WiFi, and switch configuration. Turnkey solutions.',
        metaDescription: 'Office network installation in Barcelona. Cabling + rack + WiFi + configuration. Turnkey solutions. ☎ +34 605 974 605',
        cta: 'Looking to set up your office network?',
        features: [
            { icon: '🏢', title: 'Complete solution', text: 'Design, cabling, racks, WiFi, and configuration all in a single service.' },
            { icon: '📐', title: 'Tailored layout', text: 'We analyze your office space to optimize the distribution of endpoints.' },
            { icon: '📡', title: 'Business WiFi', text: 'Professional access points ensuring blanket coverage without dead zones.' },
            { icon: '⚙️', title: 'Configuration', text: 'Switch setup, VLAN configuration, and network segmentation.' },
            { icon: '🔒', title: 'Security', text: 'Segmented systems offering secure network access for employees and guests.' },
            { icon: '📋', title: 'Documentation', text: 'Network floor plans, labeling, and complete post-installation technical documentation.' },
        ],
        faq: [
            { q: 'How much does it cost to set up an office network?', a: 'It depends on the scale: a 10-workstation setup starts around €1,500; a 20-workstation setup from €3,000; and 50 workstations from €6,000.' },
            { q: 'Can you work outside of business hours?', a: 'Yes, we conduct installations during night shifts or weekends to avoid halting your daily operations.' },
        ],
    },
    {
        slug: 'instalacion-red-casa-barcelona',
        title: 'Home Network Installation Barcelona | CableCore', // Translation up to item 9
        h1: 'Domestic network installation in Barcelona',
        h2s: ['Advantages of a wired home', 'Process', 'FAQ'],
        intro: 'Ethernet network installation at home in Barcelona. Drastically improve your WiFi, eliminate dead zones, and enjoy an ultra-stable connection in every room.',
        metaDescription: 'Home network installation in Barcelona. Ethernet cable + professional WiFi. Say goodbye to dead zones. ☎ +34 605 974 605',
        cta: 'Want to upgrade your home network?',
        features: [
            { icon: '🏠', title: 'Network all over', text: 'Ethernet ports spanning your living room, home office, bedrooms, and common areas.' },
            { icon: '📡', title: 'WiFi without dead spots', text: 'Hardwired access points guarantee flawless WiFi throughout your home.' },
            { icon: '🎮', title: 'Gaming & Streaming', text: 'Zero buffering and minimal latency for online gaming and 4K media consumption.' },
            { icon: '💼', title: 'Teleworking', text: 'A completely stable connection for uninterrupted video conferences and remote work.' },
            { icon: '🔧', title: 'Discreet setup', text: 'Aesthetic mini trunking or embedded conduits for a virtually invisible installation.' },
            { icon: '💰', title: 'Competitive pricing', text: 'Starting at €180 for 2 networked points, and from €350 for a full 4-point setup.' },
        ],
        faq: [
            { q: 'Can Ethernet be installed in an already built apartment?', a: 'Yes, we utilize decorative trunking or leverage existing empty telecommunications tubes. For renovations, we can seamlessly embed the cables.' },
            { q: 'How many network points do I need at home?', a: 'We recommend at least 2 points (living room and office). An ideal setup includes 4 points, covering bedrooms.' },
        ],
    },
    {
        slug: 'instalacion-patch-panel-barcelona',
        title: 'Patch Panel Installation Barcelona | CableCore',
        h1: 'Patch panel installation in Barcelona',
        h2s: ['Advantages of a patch panel', 'Process', 'FAQ'],
        intro: 'Professional patch panel installation in Barcelona. Organize your network, simplify changes, and dramatically reduce connection errors with a Cat6/Cat6A/Cat7 patch system.',
        metaDescription: 'Patch panel installation in Barcelona. Professional organization of Cat6/Cat6A/Cat7 networks. ☎ +34 605 974 605',
        cta: 'Do you need a patch panel?',
        features: [
            { icon: '🔗', title: 'Total organization', text: 'Every cable is meticulously identified and terminated into a centralized hub.' },
            { icon: '🔄', title: 'Easy changes', text: 'Reconfigure network endpoints easily without altering the permanent backbone cabling.' },
            { icon: '📐', title: 'Cat6/Cat6A/Cat7', text: 'Patch panels ranging across 12, 24, and 48 ports for any category.' },
            { icon: '🏷️', title: 'Labeling', text: 'A professional labeling system allowing immediate endpoint identification.' },
            { icon: '🗄️', title: 'Rack integration', text: 'Standardized compatibility with 19" wall and floor racks.' },
            { icon: '✅', title: 'Testing', text: 'Every single terminated port is tested with a professional diagnostic tester.' },
        ],
        faq: [
            { q: 'What exactly is a patch panel?', a: 'A patch panel is a centralized hardware hub where building cables terminate. Short patch cords simply link these ports to your network switch.' },
        ],
    },
    {
        slug: 'instalacion-red-barcelona',
        title: 'Network Installation in Barcelona | CableCore — Network Experts',
        h1: 'Network installation in Barcelona',
        h2s: ['All our network services in Barcelona', 'Neighborhoods and areas we cover', 'Frequently asked questions'],
        intro: "CableCore is your network installation company in Barcelona, headquartered in Badalona. We've completed over 500 installations across Barcelona city and its metropolitan area: structured cabling in Cat6/Cat6A/Cat7, fiber optics, racks, business WiFi, and home networks. In-house technicians, no subcontractors. Quote within 24 hours.",
        metaDescription: 'Network installation in Barcelona. +500 projects completed. Cat6/Cat6A/Cat7 cabling, fiber optics, racks and WiFi. In-house technicians. Free quote ☎ +34 605 974 605',
        cta: 'Need network installation in Barcelona?',
        features: [
            { icon: '🌐', title: 'Full-service networking', text: 'Cat6/Cat6A/Cat7 cabling, fiber optics, racks, patch panels, business WiFi and switch configuration — all from a single provider.' },
            { icon: '🏢', title: 'Businesses and offices', text: 'Turnkey networks for offices in 22@, Diagonal, Eixample and Zona Franca. Design, installation and documentation included.' },
            { icon: '🏠', title: 'Homes and apartments', text: 'Ethernet cabling for remote work, gaming and streaming in flats across Gràcia, Sarrià, Les Corts and Sant Andreu.' },
            { icon: '🏭', title: 'Industrial warehouses', text: "Rugged industrial cabling for companies in Zona Franca, Polígon Pratenc, Polígon Mas Blau and Barcelona's industrial estates." },
            { icon: '📍', title: 'The whole metropolitan area', text: "We cover Barcelona city, Badalona (our headquarters), L'Hospitalet, Cornellà, Sant Cugat, Sabadell, Terrassa and the entire metropolitan region." },
            { icon: '✅', title: '5-year warranty', text: 'Every installation includes professional testing, documentation and a 5-year warranty on materials and labor.' },
        ],
        faq: [
            { q: 'How much does network installation cost in Barcelona?', a: 'An installed Cat6 point starts at €110 including VAT. A Cat6A U/FTP point starts at €130 including VAT. A 10-desk office (Cat6A cabling + rack + patch panel) starts at €2,200 including VAT. A 4-point home installation starts at €500 including VAT. Ask for a free, no-obligation quote.' },
            { q: 'How long does a network installation take in Barcelona?', a: "A home with 4-8 points takes 1 day. A 15-20 point office takes 2-3 days. An industrial project with 50+ points takes 1-2 weeks. We also work weekends so your business doesn't have to stop." },
            { q: 'Do you work across all of Barcelona city?', a: 'Yes, we cover every district: Eixample, Gràcia, Sant Martí (22@), Sants-Montjuïc, Zona Franca, Horta-Guinardó, Nou Barris, Sant Andreu, Sarrià-Sant Gervasi and Les Corts.' },
            { q: 'Do you subcontract the work?', a: "No. Every job is carried out by CableCore's own staff. No middlemen, no surprises. The technician who does the site visit is the same one who does the installation." },
            { q: 'Can you install WiFi as well as cabling?', a: 'Yes. We complement Ethernet cabling with business-grade WiFi access points (Ubiquiti, TP-Link EAP) for full coverage. Cable is the backbone; WiFi covers the mobile areas.' },
            { q: 'Are you a local company or do you subcontract?', a: "We're a local company based in Badalona. We don't subcontract. The technicians who visit are the same ones who install, which guarantees continuity and accountability." },
            { q: 'Which cable — Cat6, Cat6A or Cat7 — do you recommend for an office in Barcelona?', a: "For new offices we always recommend Cat6A U/FTP. It supports 10 Gbps up to 100 meters and is future-proof. Cat6 is fine for renovations and homes. Cat7 doesn't add real advantages over Cat6A and is more expensive and less flexible." },
            { q: 'Can you install networks outside business hours in Barcelona?', a: "Yes. For offices in 22@, Eixample and other business districts we offer night and weekend installation so we don't interrupt your company's activity." },
            { q: 'Do you install indoor fiber optics (FTTO) in Barcelona?', a: 'Yes. For projects needing more than 10 Gbps of bandwidth or long runs inside a building, we install indoor fiber with LC or SC connectors and certified patch cords.' },
        ],
        richSections: [
            {
                h2: 'Types of network installation we carry out in Barcelona',
                paragraphs: [
                    'For offices in 22@, Eixample or Diagonal, we install structured Cat6A cabling with a rack, patch panel and managed switch, following the TIA-568-C.2 standard. The result is a professional network with full documentation, channel-by-channel testing and a 5-year warranty.',
                    'For homes and flats in Gràcia, Sarrià or Sant Andreu, we use Cat6 cabling run through decorative trunking or embedded in the wall. In a single working day we install between 4 and 8 network points, preparing the home for remote work, 4K streaming and NAS devices.',
                    'For industrial warehouses in Zona Franca, Polígon Pratenc or Badalona Sud, we work with Cat6A or Cat7 cabling in metal tray or rigid conduit, resistant to electromagnetic interference and vibration. We configure VLANs to separate production, administration and CCTV traffic.',
                ],
            },
            {
                h2: 'Cat6A cabling: the recommended standard for Barcelona in 2025',
                paragraphs: [
                    'Cat6A (Category 6 Augmented) cable is the professional standard for installations in Barcelona in 2025. It supports 10 Gbps speeds up to 100 meters, reduces alien crosstalk (AXT) and is compatible with PoE++ for powering 4K cameras, WiFi 6E access points and high-power IP phones.',
                    'Compared to standard Cat6, Cat6A has a larger diameter (6-8 mm vs 5-6 mm) and needs deeper back boxes. On projects with many network points, it\'s important to plan for this extra space in the conduit. At CableCore we work exclusively with certified Cat6A U/FTP cable from brands like Belden, Nexans or Prysmian to guarantee performance throughout the installation\'s lifetime.',
                    'If your company in Barcelona plans to adopt 10 Gbps technology within the next 5-10 years, investing in Cat6A now is more cost-effective than redoing the installation later. The extra cost of Cat6A over Cat6 is roughly €10-15 per installed point.',
                ],
            },
            {
                h2: 'Network installation prices in Barcelona (2025)',
                paragraphs: [
                    'Network installation prices in Barcelona vary depending on the type of project, the cabling chosen and access to the building. As a rough guide: an installed Cat6 point with faceplate, trunking and certification test starts at €110 including VAT. A Cat6A U/FTP point (the standard for offices) starts at €130 including VAT. Cat6A S/FTP for industrial environments starts at €155 including VAT.',
                    'A basic installation for a 10-desk office (Cat6A U/FTP cabling + 12U rack + patch panel + 24-port switch) costs roughly €2,200-3,000 including VAT, depending on the finish and complexity. For homes, a 4-point Cat6 network in decorative trunking starts from €500 including VAT.',
                    "All quotes include a free technical site visit, certified materials, channel-by-channel certification testing and a 5-year warranty. Request a no-obligation quote — we reply within 24 hours.",
                ],
            },
            {
                h2: 'Neighborhoods and areas of Barcelona where we install networks',
                paragraphs: [
                    'We cover every district of Barcelona city: Eixample (offices and hotels), Gràcia (flats and studios), Sant Martí and 22@ (startups and tech companies), Sants-Montjuïc and Zona Franca (industry and logistics), Horta-Guinardó, Nou Barris, Sant Andreu, Sarrià-Sant Gervasi and Les Corts.',
                    "We also operate across the entire Barcelona metropolitan area: Badalona (our headquarters, response time under 20 minutes), L'Hospitalet de Llobregat, Cornellà, Esplugues, Sant Joan Despí, Gavà, Castelldefels, Viladecans, Sant Boi, Molins de Rei, Martorell, Sant Cugat del Vallès, Cerdanyola, Sabadell, Terrassa, Mataró and Granollers.",
                ],
            },
        ],
    },
    {
        slug: 'instalacion-red-hospitalet',
        title: "Network Installation L'Hospitalet de Llobregat | CableCore",
        h1: "Network installation in L'Hospitalet de Llobregat",
        h2s: ["Network services in L'Hospitalet", "Areas we cover in L'Hospitalet", 'Frequently asked questions'],
        intro: "Network installation in L'Hospitalet de Llobregat, Catalonia's second most populous city. We cover every business zone in L'Hospitalet: Gran Via, Fira de Barcelona, Zona Franca and the Torrassa industrial estate. Cat6/Cat6A cabling for offices, retail premises and homes. Quote the same day.",
        metaDescription: "Network installation in L'Hospitalet de Llobregat. Coverage in Gran Via, Fira, Zona Franca and Torrassa. Cat6/Cat6A/Cat7. Free quote. ☎ +34 605 974 605",
        cta: "Need network installation in L'Hospitalet?",
        features: [
            { icon: '🏢', title: 'Gran Via and Fira de Barcelona', text: "We install networks in the office towers along Gran Via and in the venues and hotels around Fira de Barcelona in L'Hospitalet." },
            { icon: '🏭', title: 'Zona Franca and industrial estates', text: "Industrial cabling for warehouses in Zona Franca and the Torrassa industrial estate, frequently accessed from L'Hospitalet." },
            { icon: '🏠', title: 'Residential neighborhoods', text: 'Ethernet networks in flats across Collblanc, La Torrassa, Santa Eulàlia, Les Planes and Centre for remote work and streaming.' },
            { icon: '🛍️', title: 'Retail premises', text: "Cabling for shops, clinics and consultancies along L'Hospitalet's commercial strip and the L'Illa Diagonal shopping center." },
            { icon: '⚡', title: 'Fast response', text: "From Badalona we reach L'Hospitalet in under 30 minutes. Same-day site visits when available." },
            { icon: '📋', title: 'Free quote', text: "Free technical visit in L'Hospitalet. Detailed quote within 24 hours." },
        ],
        faq: [
            { q: "How much does network installation cost in L'Hospitalet?", a: "We apply the same prices as Barcelona city. An installed Cat6 point starts at €110 including VAT, with no travel surcharge for L'Hospitalet. Cat6A U/FTP starts at €130 including VAT." },
            { q: "Do you install in the Gran Via L'Hospitalet office buildings?", a: 'Yes, we have experience in the Gran Via office area, including towers and open-plan floors. We work outside business hours when needed.' },
            { q: "Can you install a network in a flat in La Torrassa or Collblanc?", a: "Yes, we cover every neighborhood in L'Hospitalet. For flats we use decorative trunking or run through existing conduits to avoid building work." },
            { q: "How quickly can you get to L'Hospitalet?", a: "Our headquarters is in Badalona, but L'Hospitalet is less than 30 minutes away. We can do a same-day site visit if you contact us before 2pm." },
            { q: "What kind of cabling do you install in L'Hospitalet?", a: "We install Cat6, Cat6A and indoor fiber optics. For new offices we recommend Cat6A U/FTP, which supports 10 Gbps and is PoE++ compatible for cameras and WiFi 6. For renovations and homes, Cat6 is more than enough." },
            { q: "How much does a full office network cost in L'Hospitalet?", a: "A 10-desk office with Cat6A cabling, a 12U rack, a 24-port patch panel and a managed switch costs roughly €2,000-2,600 in L'Hospitalet, with no travel surcharge." },
        ],
        richSections: [
            {
                h2: "Network installation in L'Hospitalet: sectors and areas",
                paragraphs: [
                    "L'Hospitalet de Llobregat is Catalonia's second most populous city and home to one of Spain's busiest business corridors. Gran Via Sud, with its office towers and hotels, accounts for much of our activity here: we install structured Cat6A networks for companies that need high availability and guaranteed bandwidth.",
                    "Zona Franca, managed from L'Hospitalet, is another key hub where we carry out industrial installations. We design VLAN-segregated networks to separate production, IP cameras and administration, using Cat6A cabling in metal tray or rigid conduit depending on site conditions.",
                    "In the residential neighborhoods of Collblanc, La Torrassa and Santa Eulàlia we work with individuals who work from home and need a reliable Ethernet connection for remote work and streaming. We use decorative trunking or existing conduits to keep the impact on the flat to a minimum.",
                ],
            },
            {
                h2: "Network installation prices in L'Hospitalet de Llobregat",
                paragraphs: [
                    "We apply the same prices as Barcelona city, with no travel surcharge for L'Hospitalet. An installed Cat6 point with faceplate and certification test starts at €110 including VAT. Cat6A U/FTP starts at €130 per point including VAT. Cat6A S/FTP starts at €155 including VAT. The technical site visit is always free.",
                    "For office projects in L'Hospitalet with 10-20 desks, the estimated budget ranges from €2,200 to €4,000 including VAT depending on complexity (Cat6A cabling, rack, patch panel, switch and basic network configuration). Request a quote online and we'll reply within 24 hours.",
                ],
            },
        ],
    },
    {
        slug: 'instalacion-red-badalona',
        title: 'Network Installation Badalona | CableCore — Your Local Company',
        h1: 'Network installation in Badalona',
        h2s: ['CableCore: your local company in Badalona', 'Neighborhoods and areas we cover', 'Frequently asked questions'],
        intro: 'CableCore is headquartered at Carrer Vitor Balaguer 33, Badalona. We are your network installation company in Badalona: we know the city, its industrial estates (Badalona Sud, Mas Rampinyo) and its neighborhoods inside out. Minimal response time — we reach anywhere in Badalona in under 20 minutes.',
        metaDescription: 'Network installation in Badalona. Local company headquartered in Badalona. Industrial estates, offices, homes. Same-day response. Free quote. ☎ +34 605 974 605',
        cta: 'Need network installation in Badalona?',
        features: [
            { icon: '📍', title: 'Headquartered in Badalona', text: "Our office is at Carrer Vitor Balaguer 33, Badalona. We're your local network installer, not a Barcelona company that happens to visit Badalona." },
            { icon: '🏭', title: 'Industrial estates', text: 'Experience across the Badalona Sud and Mas Rampinyo industrial estates, Montigalà and the warehouses along the C-31.' },
            { icon: '🏠', title: 'Every neighborhood', text: 'We install in Centre, Llefià, La Salut, Gorg, Sant Roc, Artigues, Bufalà, Sistrells and every residential area of Badalona.' },
            { icon: '🏢', title: 'Offices and shops', text: 'Cabling for offices, clinics, academies and retail premises along Av. Martí Pujol and around the Mercat Municipal.' },
            { icon: '⚡', title: 'Response under 20 minutes', text: 'Being based in Badalona, we can arrange an urgent site visit with arrival times under 20 minutes in most cases.' },
            { icon: '🛡️', title: 'Local trust and guarantee', text: 'A well-known company in Badalona with over 10 years of activity. 5-year warranty on every installation.' },
        ],
        faq: [
            { q: 'Where is your office in Badalona?', a: "We're at Carrer Vitor Balaguer 33, 08914 Badalona. You're welcome to visit or call +34 605 974 605 to arrange a technical visit." },
            { q: 'Do you cover every neighborhood in Badalona?', a: 'Yes, we cover all of Badalona: Centre, Llefià, La Salut, Gorg, Sant Roc, Artigues, Bufalà, Sistrells, Pomar, Montigalà and the industrial area.' },
            { q: "Do you do installations in Badalona's industrial estates?", a: 'Yes, we have extensive experience in the Badalona Sud and Mas Rampinyo estates. We install Cat6A and Cat7 industrial networks with IP-rated conduit.' },
            { q: 'How much does network installation cost in Badalona?', a: 'An installed Cat6 point starts at €110 including VAT, with absolutely no surcharge for being in Badalona. As a local company, our internal travel is free.' },
        ],
    },
    {
        slug: 'instalacion-red-sabadell',
        title: 'Network Installation Sabadell | CableCore',
        h1: 'Network installation in Sabadell',
        h2s: ['Services in Sabadell and Vallès Occidental', 'Business and residential areas', 'Frequently asked questions'],
        intro: 'Network installation in Sabadell for companies across Vallès Occidental. We cover the Can Roqueta, Can Llong and Polígon Nord industrial estates, and the Eix Macià business district. Structured Cat6, Cat6A and Cat7 cabling for factories, offices and homes in Sabadell.',
        metaDescription: 'Network installation in Sabadell. Coverage in Can Roqueta, Eix Macià, industrial estates and residential areas. Cat6/Cat6A/Cat7. ☎ +34 605 974 605',
        cta: 'Need network installation in Sabadell?',
        features: [
            { icon: '🏭', title: 'Industrial estates', text: 'Cabling for warehouses and companies in Can Roqueta, Can Llong, Polígon Nord and the industrial zones south of Sabadell.' },
            { icon: '🏢', title: 'Eix Macià and city centre', text: "Structured networks for offices in Eix Macià, Plaça Catalunya and Sabadell's central shopping district." },
            { icon: '🏠', title: 'Residential neighborhoods', text: 'Ethernet networks in flats across Can Puiggener, La Creu Alta, Gràcia, Torre-Romeu and every neighborhood of Sabadell.' },
            { icon: '📡', title: 'WiFi in warehouses', text: 'Industrial access points with Cat6A backbone cabling for full WiFi coverage in storage facilities and warehouses.' },
            { icon: '📋', title: 'Quote within 24h', text: 'Get in touch today and receive a detailed quote with a materials breakdown within 24 hours.' },
            { icon: '✅', title: 'Same prices as Barcelona', text: 'No travel surcharge for Sabadell. Prices are identical to Barcelona city.' },
        ],
        faq: [
            { q: "Do you carry out installations in Sabadell's industrial estates?", a: 'Yes, we cover Can Roqueta, Can Llong, Polígon Nord and Sabadell industrial zones. We install Cat7 with IP-rated conduit for environments with dust or humidity.' },
            { q: 'How long does it take you to reach Sabadell?', a: 'From our headquarters in Badalona, we reach Sabadell in 30-40 minutes via the B-23. We can arrange a same-day site visit if you contact us before midday.' },
            { q: 'Do you install networks in detached houses in Sabadell?', a: "Yes, we install in single-family homes. We use decorative trunking or embedded cabling depending on the type of construction and the client's preference." },
        ],
    },
    {
        slug: 'instalacion-red-terrassa',
        title: 'Network Installation Terrassa | CableCore',
        h1: 'Network installation in Terrassa',
        h2s: ['Services in Terrassa', 'Industrial and business areas', 'Frequently asked questions'],
        intro: "Network installation in Terrassa for businesses and homes in Vallès Occidental. We have experience in the Ca n'Aurell, Can Parellada and Vallès Parc Empresarial industrial estates. Cat6A and Cat7 cabling for Terrassa's textile and industrial sector, plus home installations in the city centre and residential areas.",
        metaDescription: "Network installation in Terrassa. Ca n'Aurell, Can Parellada, Vallès Parc estates. Cat6/Cat6A/Cat7 for industry and homes. ☎ +34 605 974 605",
        cta: 'Need network installation in Terrassa?',
        features: [
            { icon: '🏭', title: "Terrassa's industry", text: "Shielded Cat7 cabling for the textile, metalworking and manufacturing companies of the Ca n'Aurell and Can Parellada estates." },
            { icon: '🏢', title: 'Vallès Parc Empresarial', text: 'Structured networks for offices in Vallès Parc Empresarial and the business area around Passeig de les Lletres.' },
            { icon: '🏗️', title: 'New builds and renovations', text: 'Embedded cabling in new buildings, or trunking adapted to existing premises.' },
            { icon: '📡', title: 'Business WiFi', text: 'WiFi 6 access points on a Cat6A backbone for full coverage without dead zones.' },
            { icon: '🗄️', title: 'Racks and cabinets', text: 'Telecommunications cabinet installation for Terrassa companies with centralized network management.' },
            { icon: '📋', title: 'No obligation', text: 'Free technical site visit and detailed quote. No travel charge to Terrassa.' },
        ],
        faq: [
            { q: 'Do you cover Terrassa and the surrounding area?', a: 'Yes, we carry out installations in Terrassa, Rubí, Matadepera, Ullastrell and other municipalities of Vallès Occidental. No travel surcharge.' },
            { q: 'Do you have experience with factories in Terrassa?', a: "Yes, we've installed networks in industrial warehouses in the textile and metalworking sector. We use shielded Cat7 S/FTP for environments with electromagnetic interference." },
            { q: 'What cable do you recommend for an office in Terrassa?', a: 'For offices in Terrassa we recommend Cat6A (10 Gbps). It is the current standard for new business installations and the best mid-term investment.' },
        ],
    },
    {
        slug: 'instalacion-red-sant-cugat',
        title: 'Network Installation Sant Cugat del Vallès | CableCore',
        h1: 'Network installation in Sant Cugat del Vallès',
        h2s: ['Services in Sant Cugat', 'Business parks and residential estates', 'Frequently asked questions'],
        intro: 'Professional network installation in Sant Cugat del Vallès for businesses and high-end homes. We cover the Parc Empresarial Can Sant Joan, the Polígon Industrial Les Planes, and the residential estates of Can Baró, Volpelleres and La Floresta. Premium installations using top-quality materials with discreet finishes.',
        metaDescription: 'Network installation in Sant Cugat del Vallès. Coverage in Can Sant Joan, Les Planes and residential estates. Premium installs for homes and businesses. ☎ +34 605 974 605',
        cta: 'Need network installation in Sant Cugat?',
        features: [
            { icon: '🏢', title: 'Parc Empresarial Can Sant Joan', text: 'Structured cabling for corporate headquarters and offices in the Parc Empresarial Can Sant Joan and the Les Planes estate.' },
            { icon: '🏠', title: 'Exclusive residential estates', text: "Premium Ethernet networks in homes across Can Baró, Volpelleres, La Floresta and Sant Cugat's residential estates." },
            { icon: '📐', title: 'Custom design', text: 'For large homes in Sant Cugat we design the network to optimize points per floor while minimizing visible cabling.' },
            { icon: '🔒', title: 'Secure networks for businesses', text: 'VLANs, segmentation and controlled WiFi access for companies in the business park. GDPR-compliant.' },
            { icon: '📡', title: 'Whole-property WiFi mesh', text: 'Wired-backed mesh WiFi systems for uninterrupted coverage in large homes and gardens.' },
            { icon: '✅', title: 'Discreet, high-end finishes', text: 'Flush-mounted faceplates, invisible cabling and finishes that respect the aesthetics of Sant Cugat homes.' },
        ],
        faq: [
            { q: 'Do you install networks in detached houses in Sant Cugat?', a: 'Yes, we have extensive experience with single-family homes in Sant Cugat. We install cabling on every floor with fully concealed embedded cable for an invisible finish.' },
            { q: 'How much does it cost to wire a house in Sant Cugat?', a: 'A three-storey house with 8-12 network points and WiFi mesh runs between €2,200 and €4,000 including VAT, depending on size and finish. This includes all embedded Cat6A points and a professional WiFi system.' },
            { q: 'Do you install networks in the companies at Parc Empresarial Can Sant Joan?', a: 'Yes, we have experience in the business park. We install outside business hours to avoid disrupting operations and provide full documentation.' },
            { q: 'Can embedded cabling be installed without major building work?', a: 'Yes, we use suspended-ceiling routing or minimal wall chasing techniques. In new-build homes we always recommend fully embedded cabling.' },
        ],
    },
    {
        slug: 'instalacion-red-cornella',
        title: 'Network Installation Cornellà de Llobregat | CableCore',
        h1: 'Network installation in Cornellà de Llobregat',
        h2s: ['Services in Cornellà and Baix Llobregat', 'Industrial estates and business areas', 'Frequently asked questions'],
        intro: 'Network installation in Cornellà de Llobregat and Baix Llobregat. We cover the Polígon Industrial Gran Via Sud, the Almeda industrial zone and the Parc Empresarial de Cornellà. We also install in the residential neighborhoods of Sant Ildefons, Gavarra and Almeda. A trusted company across Baix Llobregat.',
        metaDescription: 'Network installation in Cornellà de Llobregat. Polígon Gran Via Sud, Almeda, Parc Empresarial. Baix Llobregat. Cat6/Cat6A/Cat7. ☎ +34 605 974 605',
        cta: 'Need network installation in Cornellà?',
        features: [
            { icon: '🏭', title: 'Polígon Gran Via Sud', text: 'Structured cabling for warehouses in the Polígon Industrial Gran Via Sud, the largest in Baix Llobregat.' },
            { icon: '🏢', title: 'Parc Empresarial de Cornellà', text: 'Networks for offices and companies in the Parc Empresarial de Cornellà and the Almeda area.' },
            { icon: '🏠', title: "Cornellà's neighborhoods", text: "Installations in flats across Sant Ildefons, Gavarra, Almeda, Sant Joan Espí and Cornellà city centre." },
            { icon: '📍', title: 'All of Baix Llobregat', text: 'From Cornellà we cover Esplugues, Sant Joan Despí, Sant Just Desvern, Molins de Rei and other Baix Llobregat municipalities.' },
            { icon: '⚡', title: 'Fast service', text: 'Quote within 24 hours, installation on the date you choose. No travel surcharge for Baix Llobregat.' },
            { icon: '🛡️', title: '5-year warranty', text: 'Extended 5-year warranty on all materials and labor.' },
        ],
        faq: [
            { q: 'Do you cover Cornellà de Llobregat?', a: 'Yes, we cover Cornellà and every municipality in Baix Llobregat: Esplugues, Sant Joan Despí, Sant Just, El Prat, Gavà, Viladecans, Castelldefels and more.' },
            { q: "Do you install in Cornellà's industrial estates?", a: 'Yes, we have experience in the Polígon Gran Via Sud and the Almeda industrial zone. We install Cat6A and Cat7 for industrial environments.' },
            { q: 'How much does network installation cost in Cornellà?', a: 'We apply the same prices as Barcelona city. An installed Cat6 point starts at €110 including VAT, with no travel surcharge.' },
        ],
    },
    {
        slug: 'instalacion-red-sant-boi',
        title: 'Network Installation Sant Boi de Llobregat | CableCore',
        h1: 'Network installation in Sant Boi de Llobregat',
        h2s: ['Services in Sant Boi', 'Areas and neighborhoods', 'Frequently asked questions'],
        intro: 'Network installation in Sant Boi de Llobregat. We cover the Polígon Industrial Fontsanta, the Parc Industrial de Can Gambús, and the residential neighborhoods of Marianao, Camps Blancs and Vinyets. Ethernet cabling for homes, shops and businesses in Sant Boi and the southern Baix Llobregat municipalities.',
        metaDescription: 'Network installation in Sant Boi de Llobregat. Polígon Fontsanta, Can Gambús, Marianao and Camps Blancs. Cat6/Cat6A/Cat7. ☎ +34 605 974 605',
        cta: 'Need network installation in Sant Boi?',
        features: [
            { icon: '🏭', title: 'Polígon Fontsanta and Can Gambús', text: 'Industrial cabling for warehouses and companies in the Polígon Industrial Fontsanta and the Parc Industrial de Can Gambús.' },
            { icon: '🏠', title: 'Residential neighborhoods', text: 'Ethernet networks in flats across Marianao, Camps Blancs, Vinyets, El Molí and Sant Boi city centre.' },
            { icon: '🏢', title: 'Local businesses', text: 'Cabling for clinics, academies, consultancies and shops in Sant Boi.' },
            { icon: '📡', title: 'WiFi without dead zones', text: 'Wired access points to eliminate weak-signal areas in homes and premises.' },
            { icon: '📍', title: 'Southern Baix Llobregat', text: 'We cover Sant Boi, Viladecans, Gavà, Castelldefels and all coastal Baix Llobregat municipalities.' },
            { icon: '✅', title: 'Full warranty', text: 'Every point installed and tested. 5-year warranty on materials and work.' },
        ],
        faq: [
            { q: 'Do you install networks in Sant Boi de Llobregat?', a: 'Yes, we cover Sant Boi and the entire southern Baix Llobregat area: Viladecans, Gavà, Castelldefels and near El Prat airport.' },
            { q: "Do you install in Sant Boi's industrial estates?", a: 'Yes, we install in the Polígon Fontsanta and Can Gambús. For industrial environments we recommend Cat6A or Cat7 depending on the level of interference.' },
            { q: 'How much does network installation cost in Sant Boi?', a: 'Same prices as Barcelona. An installed Cat6 point starts at €110 including VAT. No travel surcharge for Baix Llobregat.' },
        ],
    },
    {
        slug: 'instalacion-red-castelldefels',
        title: 'Network Installation Castelldefels | CableCore',
        h1: 'Network installation in Castelldefels',
        h2s: ['Networks for homes in Castelldefels', 'Outdoor and garden WiFi', 'Frequently asked questions'],
        intro: 'Network installation in Castelldefels for houses, apartments and businesses along the Garraf coast. We specialize in single-family homes with gardens and second residences: we run cabling across every floor and install outdoor WiFi access points for terraces and pools. We also cover the Parc Empresarial de Castelldefels and the Gavà Mar area.',
        metaDescription: 'Network installation in Castelldefels. Houses, second homes, outdoor garden WiFi. Parc Empresarial Castelldefels. ☎ +34 605 974 605',
        cta: 'Need network installation in Castelldefels?',
        features: [
            { icon: '🏖️', title: 'Houses and second residences', text: 'Specialists in homes across Castelldefels, Gavà Mar and Sitges. Ethernet cabling on every floor plus WiFi for gardens and pools.' },
            { icon: '📡', title: 'Professional outdoor WiFi', text: 'IP65-rated outdoor access points, wired for perfect WiFi coverage on terraces, gardens and by the pool.' },
            { icon: '🏢', title: 'Parc Empresarial de Castelldefels', text: 'Structured cabling for tech companies and offices in the Parc Empresarial de Castelldefels next to the B-23.' },
            { icon: '🎮', title: 'Gaming and smart home', text: 'Low-latency networks for competitive gaming and technical support for smart-home devices.' },
            { icon: '🏘️', title: 'The whole Garraf coast', text: 'Service in Castelldefels, Gavà, Gavà Mar, Sitges, Vilanova i la Geltrú and other Garraf coastal municipalities.' },
            { icon: '🛡️', title: 'Outdoor-rated materials', text: 'Cables and connectors certified for outdoor use, resistant to humidity and sun exposure on the Mediterranean coast.' },
        ],
        faq: [
            { q: 'Do you install networks in houses in Castelldefels?', a: 'Yes, it is one of our main services in the area. We wire every floor with embedded cable or trunking and add outdoor WiFi for the garden and terrace.' },
            { q: 'Can you install WiFi in the garden or by the pool?', a: 'Yes, we install certified IP65 outdoor access points, resistant to water and sun. They are wired from inside the house for a stable signal across the whole plot.' },
            { q: 'Do you install in second residences?', a: 'Yes, we work on second homes. We can coordinate access with a cleaner or caretaker and send you the installation report by email.' },
            { q: 'How much does it cost to wire a house in Castelldefels?', a: 'A two-storey house with 6-10 network points and outdoor WiFi costs between €1,800 and €3,200 including VAT, depending on size and finish. Request a no-obligation quote.' },
        ],
    },
    {
        slug: 'instalacion-red-mataro',
        title: 'Network Installation Mataró | CableCore',
        h1: 'Network installation in Mataró',
        h2s: ['Services in Mataró and Maresme', 'Industrial and business areas', 'Frequently asked questions'],
        intro: "Network installation in Mataró for businesses and homes across Maresme. We cover the Pla d'en Boet industrial estate, the Parc Empresarial de la Mata, and the Mataró Park shopping centre. Cat6, Cat6A and Cat7 cabling for Mataró's industry, offices in the city centre, and homes in Els Molins, Cirera and Rocafonda.",
        metaDescription: "Network installation in Mataró. Pla d'en Boet industrial estate, Parc Empresarial La Mata, centre and residential areas. Cat6/Cat6A/Cat7. ☎ +34 605 974 605",
        cta: 'Need network installation in Mataró?',
        features: [
            { icon: '🏭', title: "Pla d'en Boet industrial estate", text: "Structured cabling for companies in the Pla d'en Boet industrial estate, Mataró's largest, home to over 300 businesses." },
            { icon: '🏢', title: 'City centre and shopping district', text: 'Networks for offices, consultancies and shops in Mataró city centre and around La Rambla.' },
            { icon: '🏠', title: 'Residential neighborhoods', text: 'Ethernet installation in flats and houses across Els Molins, Cirera, Rocafonda, Vista Alegre and Cerdanyola.' },
            { icon: '🏪', title: 'Mataró Park', text: 'Experience with retail premises and offices around the Mataró Park shopping centre and the retail zone.' },
            { icon: '⚡', title: 'Quote within 24h', text: 'We reply with a quote within 24 hours and can arrange a next-day site visit if needed.' },
            { icon: '📊', title: 'Professional testing', text: 'We measure every cable pair with a professional analyzer. Testing report included.' },
        ],
        faq: [
            { q: 'Do you reach Mataró?', a: 'Yes, we cover the whole Maresme region from Montgat to Mataró and Arenys de Mar. No travel surcharge.' },
            { q: 'Are prices the same as in Barcelona?', a: 'Yes, our prices are identical across the whole metropolitan area and Maresme. No distance surcharges.' },
            { q: "Do you install in Mataró's industrial estates?", a: "Yes, we have experience in the Pla d'en Boet estate and the Parc Empresarial La Mata. We install Cat6A for offices and Cat7 for industrial warehouses." },
        ],
    },
    {
        slug: 'instalacion-red-granollers',
        title: 'Network Installation Granollers | CableCore',
        h1: 'Network installation in Granollers',
        h2s: ['Services in Granollers and Vallès Oriental', 'Industrial estates and business areas', 'Frequently asked questions'],
        intro: 'Network installation in Granollers for businesses across Vallès Oriental. We cover the Les Franqueses and Can Prat industrial estates, the Parque Industrial de Granollers, and the area around the Mercado Central. Cat6, Cat6A and Cat7 cabling for Vallès Oriental industry, offices in Granollers city centre, and homes in La Garriga, Mollet and Canovelles.',
        metaDescription: 'Network installation in Granollers. Les Franqueses, Can Prat, Parque Industrial estates. Vallès Oriental. Cat6/Cat6A/Cat7. ☎ +34 605 974 605',
        cta: 'Need network installation in Granollers?',
        features: [
            { icon: '🏭', title: 'Vallès Oriental industrial estates', text: 'Structured cabling for companies in the Les Franqueses, Can Prat and Granollers-Canovelles industrial parks.' },
            { icon: '🏢', title: 'Granollers city centre', text: 'Networks for offices and shops in Granollers city centre and around the Mercado Central.' },
            { icon: '🏠', title: 'Vallès Oriental municipalities', text: 'Ethernet installation in homes across Granollers, Mollet del Vallès, La Garriga, Parets del Vallès and Cardedeu.' },
            { icon: '📡', title: 'WiFi for warehouses', text: 'WiFi 6 access points on a Cat6A backbone for full coverage in storage facilities and industrial warehouses.' },
            { icon: '📋', title: 'Quote within 24h', text: 'Get in touch today for a detailed quote within 24 hours. Free, no-obligation site visit in Granollers.' },
            { icon: '✅', title: '5-year warranty', text: 'Quality materials backed by an extended 5-year warranty on all work.' },
        ],
        faq: [
            { q: 'Do you carry out installations in Granollers?', a: 'Yes, we cover Granollers and all of Vallès Oriental: Mollet del Vallès, La Garriga, Parets del Vallès, Cardedeu, Les Franqueses and Aiguafreda.' },
            { q: "Do you install in Granollers' industrial estates?", a: 'Yes, we work in the Les Franqueses estate, Can Prat and the Parc Industrial de Granollers. For industrial warehouses we recommend Cat6A or Cat7 depending on interference.' },
            { q: 'Are prices the same as in Barcelona?', a: 'Yes, the same prices apply across Vallès Oriental. No travel surcharge for Granollers.' },
        ],
    },
    {
        slug: 'instalacion-fibra-optica-barcelona',
        title: 'Fiber Optic Installation Barcelona | CableCore',
        h1: 'Fiber optic installation in Barcelona',
        h2s: ['Why install fiber optics?', 'Types of installation', 'Frequently asked questions'],
        intro: 'Highly specialized professional fiber optic installation engineering servicing Barcelona. Mastering precision arc fusion splicing, rigid single-mode or adaptable multimode backbone threading, immaculate SC/APC endpoint distribution, alongside rigorous strict OTDR empirical testing. Optimizing intense corporations, sprawling vertical housing complexes, and broad neighborhood estates.',
        metaDescription: 'Fiber optic installation correctly executed in Barcelona. Surgical fusion splicing, intense single/multimode array tracking, OTDR testing. ☎ +34 605 974 605',
        cta: 'Looking proactively to construct immense fiber optic backbone pathways across Barcelona?',
        features: [
            { icon: '🔆', title: 'Single-mode & Multimode', text: 'Deploying high-efficiency single-mode (SM) trunk lines ranging distinctly up toward 12-core configurations perfectly complementing shorter localized high-bandwidth multimode OM3/OM4 jumps.' },
            { icon: '🔥', title: 'Precision Arc Fusion', text: 'Execution relying fundamentally upon next-generation electrical arc splicing mechanics severely crushing structural line attenuation assuring flawless ultimate beam integrity.' },
            { icon: '🔌', title: 'SC/APC Connectorization', text: 'Clean physical port transitions heavily utilizing premium SC/APC pigtail completions alongside high-fidelity symmetrical bridging couplers guaranteeing optimal junction transmission.' },
            { icon: '🗄️', title: 'Racking & Organizational Trays', text: 'Thoroughly methodical physical mounting establishing dedicated optical staging racks systematically shielding microscopic fusion joints housed perfectly within isolated 1U protective splice enclosures.' },
            { icon: '📊', title: 'OTDR Verification', text: 'Exacting microscopic photonic pulse examinations rigorously diagnosing single specific internal fiber strand variables comprehensively cataloging conclusive structural performance margins.' },
            { icon: '🏢', title: 'Vertical Estate Integration', text: 'Purpose-built FTTH internal vertical riser drops methodically distributing pure core network capacity systematically starting from base communal telecom vaults extending independently delivering dedicated 2-port SC/APC nodes up arriving securely entering completely distinct apartments.' },
        ],
        faq: [
            { q: 'How does exact pricing regarding internal fiber optic endpoint generation scale operating locally throughout Barcelona?', a: 'Financial estimation hinges directly correlating sheer distance routing measured concurrently against total discrete endpoints ordered. Structurally speaking, individual finished node completions (comprising requisite splicing routines thoroughly validated) initiate routinely beginning around €55. Contact experts promptly unlocking localized no-risk operational appraisals.' },
            { q: 'What distinguishing factor structurally defines diverging single-mode versus multimode architectural deployments?', a: 'Single-mode (SM) infrastructures dominate enormous distance transmissions (remaining reliable out striking upwards closing 100 kilometers) serving practically exclusively grounding prevalent FTTH broadband network standards. Conversely, multimode arrays (OM3/OM4 specifications) focus primarily flooding hyper-speed 10-100 Gbps torrents rapidly sweeping distinctly confined internal corporate datacenters.' },
            { q: 'Are dedicated arc fusion services handled internally?', a: 'Without exception. Micro-splicing protocols definitively function utilizing heavy dedicated continuous-arc processing mechanics. Crucially furthermore, successive subsequent junctions strictly face uncompromising OTDR probing guaranteeing flawless microscopic operational efficacy.' },
            { q: 'Do deployment vectors comprehensively accommodate sprawling multi-tenant vertical housing constructs?', a: 'Absolutely. Formidable dedicated FTTH trunk distributions systematically navigate existing internal vertical riser shafts initiating physically deep inside underlying structural concrete basements successively segregating singular dedicated single-mode lifelines penetrating precisely terminating delivering discrete distinct SC/APC rosettes internally powering individually occupied residences.' },
        ],
    },
    {
        slug: 'instalacion-fibra-optica-empresas-barcelona',
        title: 'Corporate Fiber Optics Barcelona | CableCore',
        h1: 'Enterprise fiber optic installation in Barcelona',
        h2s: ['Advanced Enterprise Solutions', 'Underlying Equipment & Logistics', 'Frequently asked questions'],
        intro: 'Heavy-duty enterprise fiber optic routing fundamentally commanding intense commercial data loads operating inside Barcelona. Actively fusing deeply critical multi-campus interconnects reliably constructing permanent massive organizational backbones capable of continuously handling relentless hyper-speed transmissions integrating tightly braided single and multimode core lines generating ironclad operational networking.',
        metaDescription: 'Aggressive professional enterprise fiber optic pathways built across Barcelona. Formidable inter-campus routing bridging unrelenting 10/40/100 Gbps. ☎ +34 605 974 605',
        cta: 'Demands rapidly dictating massive infrastructural throughput upgrades securing overriding enterprise continuity?',
        features: [
            { icon: '🚀', title: 'Hyper-Bandwidth', text: 'Immaculate photonic conduit staging easily swallowing devastating operational data spikes scaling progressively managing extreme sustained 10, 40, actively pushing massive 100 Gbps uncompressed flowrates utilizing OM4 internal core bridging.' },
            { icon: '🏢', title: 'Campus Interconnection', text: 'Dedicated direct physical links effectively merging scattered remote operational warehousing securely integrating completely distinct isolated administrative data lakes acting effectively simulating single contiguous structural footprints.' },
            { icon: '📡', title: 'Permanent Structural Backbone', text: 'Photonic glass threading systematically deployed operating decisively acting absolutely permanently constituting fundamental central circulatory networking systems delivering totally unmatched latency compression parameters.' },
            { icon: '🔒', title: 'Uncompromising Security', text: 'Inherent optical physical properties actively maintaining totally complete immunity deflecting entirely any external hostile electromagnetic bombardment inherently simultaneously establishing severely complex exceedingly difficult unauthorized external wiretapping environments.' },
            { icon: '📐', title: 'Engineered Paradigms', text: 'Intelligent procedural layout mapping flawlessly matching uniquely specific architectural demands strictly adhering toward preserving total structural continuous up-time availability optimizing ultimate network node survivability.' },
            { icon: '✅', title: 'Conclusive OTDR Testing', text: 'Indisputable strict verification testing sweeping actively identifying microscopic photonic variance anomalies.' },
        ],
        faq: [
            { q: 'Does transitioning immediately toward encompassing fiber infrastructures demonstrably guarantee positive sweeping long-term enterprise return-on-investment parameters?', a: 'Given scenarios continuously aggressively attempting successfully managing massively crushing concurrent heavy volume streaming information matrices or bridging completely disconnected remote independent physical architectures demanding zero-compromise exceeding generalized gigabit baselines; aggressive optical implementations unequivocally represent unbeatably efficient definitively optimized supreme long-term stabilization solutions.' },
            { q: 'Do optical fiber layouts securely integrate synchronously alongside pre-existing conventional heavy copper Ethernet deployments?', a: 'Utterly. Symbiotic hybridized combinations frequently constitute dominant standardized implementation models. Invariably, optical pathways definitively act shouldering heavy intra-building core bridging loads, while existing conventional copper Cat6A distributions efficiently actively execute localized localized terminal workstation branch node segregations.' },
        ],
    },
    {
        slug: 'cableado-fibra-optica-interior-barcelona',
        title: 'Indoor Fiber Optic Cabling Barcelona | CableCore',
        h1: 'Indoor fiber optic cabling installations in Barcelona',
        h2s: ['Interior Cabling Variations', 'Material Compliance & Aesthetics', 'Frequently asked questions'],
        intro: 'Extremely intricate indoor fiber optic routing implementations carefully staging strictly discreet interior layouts stretching natively inside Barcelona. Strategically deploying tight-buffer optical protective sheathing specifically chosen guaranteeing highly reliable internal structural transmission cleanly riding neatly positioned decorative trunking channels or carefully exploiting pre-existing empty wall conduit plumbing preserving complete structural elegance.',
        metaDescription: 'Indoor fiber optic integrations carefully deployed inside Barcelona. Assuring deeply discrete aesthetics supporting utterly massive bandwidth. ☎ +34 605 974 605',
        cta: 'Seeking entirely aesthetic discrete optical fiber threading snaking securely indoors?',
        features: [
            { icon: '🏠', title: 'Interior Specialized Sourcing', text: 'Dedicated tight-buffered LSZH (Low Smoke Zero Halogen) optical strands painstakingly selected thoroughly satisfying deeply stringent legally mandated interior building fire-retardant CPR regulations.' },
            { icon: '📏', title: 'Decorative Trunking', text: 'Careful execution relying heavily surrounding highly inconspicuous miniature surface trunking lines retaining immaculate overarching pre-existing architectural visual flow patterns.' },
            { icon: '🏗️', title: 'Suspended Ceiling Drops', text: 'Methodical structural threading safely tracing expansive horizontal overhead structural routing runs establishing thoroughly invisible utterly pristine operational network layouts.' },
            { icon: '🔧', title: 'Existing Conduits', text: 'Aggressive exploratory diagnostics locating effectively mapping previously abandoned empty structural wall tubing actively minimizing extremely disruptive heavy physical masonry alterations.' },
            { icon: '🔌', title: 'Rosette Interfaces', text: 'Pristine aesthetic terminal completions relying heavily providing perfectly seated SC/APC twin-port optical wall delivery rosette housings.' },
            { icon: '🗄️', title: 'Terminal Enclosures', text: 'Dedicated micro optical staging wall enclosures guaranteeing heavily isolated flawless individual microscopic operational strand organization maximizing internal bend radiuses.' },
        ],
        faq: [
            { q: 'Does interior surface-mounted optical layout processing conspicuously drastically alter existing interior visual aesthetics?', a: 'Decisively negatively. Precise implementations lean aggressively maintaining near-invisible overall profiling intentionally exploiting extremely minute slimline flush decorative trunking segments completely melting practically disappearing naturally conforming hugging immediate interior environmental trims.' },
            { q: 'Which explicit physical cable specifications define mandated strictly indoor legal networking execution frameworks?', a: 'Implementations invariably depend entirely upon specialized distinctly dedicated tight-buffered optical configurations crucially incorporating strictly mandatory heavy LSZH regulatory safety jackets strongly limiting deadly toxic atmospheric smoke generation reliably aligning directly keeping full strict compliance facing overarching CPR European fire code legislation.' },
        ],
    },
    {
        slug: 'fusion-fibra-optica-barcelona',
        title: 'Fiber Optic Fusion Splicing Barcelona | CableCore',
        h1: 'Professional fiber optic fusion splicing in Barcelona',
        h2s: ['The Fusion Process', 'Technological Equipment', 'Frequently asked questions'],
        intro: 'Meticulously sophisticated professional optical execution specifically addressing complex fiber optic fusion splicing mandates requested actively across Barcelona. Leveraging severely advanced precise electrical arc welding systems securely merging distinct pigtail nodes definitively housed cleanly neatly resting safely inside specialized isolation splice trays comprehensively checked strictly relying executing comprehensive OTDR testing matrices.',
        metaDescription: 'Fiber splicing flawlessly achieved dominating Barcelona. Extremely advanced arc welding methodologies forcing sub-0.05 dB transmission losses. ☎ +34 605 974 605',
        cta: 'Operating under actively pressing heavy fiber splice fusion requirements?',
        features: [
            { icon: '🔥', title: 'Micro-Arc Fusion', text: 'Astounding microscopic glass welding mechanics inherently driving phenomenal next-generation continuous electric arc machinery easily shattering general threshold restrictions reliably pulling typical node attenuation completely below extreme minuscule 0.02 dB margins.' },
            { icon: '📊', title: 'OTDR Diagnostics', text: 'Subsequent immediate laser pulse analysis exhaustively verifying critically checking singular microscopic individual weld zones definitively isolating guaranteeing ensuring absolutely total flawless structural operational capabilities.' },
            { icon: '🔌', title: 'Supreme Pigtails', text: 'Pristine uncompromising endpoint completions heavily utilizing premium grade deeply seated SC/APC optical pigtail adapters strongly reinforcing subsequent flawless direct hardware connectivity interfaces.' },
            { icon: '📋', title: 'Strategic Organization', text: 'Consecutively sequenced individual microscopic fragile junctions safely systematically housed protected securely floating tightly wrapped laying completely nested resting exactly optimally inside heavy dedicated 1U rack-mounted aluminum enclosure shielding.' },
            { icon: '🏢', title: 'FTTH Deployments', text: 'Relentless aggressive structural splicing successfully coordinating spanning dense vertical segregation distribution boxes aggressively feeding tight centralized backbone consolidation telecom basement access vaults.' },
            { icon: '⚡', title: 'Critical Response', text: 'Immediate priority-status urgent field dispatch successfully rapidly isolating critically intercepting diagnosing systematically reconstructing entirely repairing severely compromised accidentally sheared primary physical optical connections operating 24/7 schedules.' },
        ],
        faq: [
            { q: 'Typically how precisely exactly does specific pricing surrounding localized optical fusion execution calculate?', a: 'Standardized operational billing typically generates flat estimations essentially establishing standard baseline €15 fixed charges reliably covering singular distinct individual junction points notably consistently generally absorbing entirely necessary thermal protective sleeving paired securely attaching accompanying premium SC/APC pigtail terminators.' },
            { q: 'Exactly how severely prolonged does generating individual physical fusion processes demand operationally?', a: 'Specifically isolating single singular junctions remarkably easily strictly consumes actively barely two rapid minutes. Correspondingly systematically extrapolating larger demanding 12-24 core multi-node arrays steadily conclude reliably heavily finishing completely definitively wrapping typically occupying merely 2-3 standard hours heavily inclusive integrating comprehensive testing procedural routines.' },
            { q: 'What anticipated attenuation variances routinely characterize heavily processed successfully finished machine welded optical junctions?', a: 'Directly utilizing uncompromising deeply advanced calibration machinery inherently forcibly pulls standard expected attenuation resistance loss metrics dramatically remarkably driving resulting margins frequently registering actively hovering firmly lower cleanly tracking well profoundly beneath strictly challenging 0.02 dB floors effortlessly bypassing normally widely accepted completely tolerable wider 0.1 dB industrial limits.' },
        ],
    },
    {
        slug: 'instalacion-ftth-edificios-barcelona',
        title: 'Building FTTH Installation Barcelona | CableCore',
        h1: 'FTTH installations for building complexes in Barcelona',
        h2s: ['Understanding FTTH Architecture', 'Installation Implementation', 'Frequently asked questions'],
        intro: 'Comprehensive profound dense vertical FTTH (Fiber To The Home) physical matrix deployments effectively dominating towering residential multi-tenant architectures proudly spanning Barcelona. Severely complex exactingly routed optical heavy backbone trunks rapidly escalating progressively advancing directly linking heavily protected subterranean centralized telecom vaults deliberately seamlessly connecting terminating directly forcefully pushing twin SC/APC delivery points establishing profound isolated internal dedicated residential apartment staging drops.',
        metaDescription: 'Decisive flawless active FTTH deployment enveloping deeply Barcelona residential buildings. Direct optical housing connections ensuring future-proof structural internet value. ☎ +34 605 974 605',
        cta: 'Urgently anticipating profoundly modernizing massive entire building communications infrastructures immediately?',
        features: [
            { icon: '🏢', title: 'Vertical Trunking', text: 'Methodical precisely organized heavily protected single-mode structural lifelines advancing flawlessly directly ascending continuously straight upward decisively stretching directly reaching continuously feeding perfectly consecutive distinct individual structural architectural building floors.' },
            { icon: '🔌', title: 'Interior Rosettes', text: 'Exacting distinct precisely clean fully separated individual dedicated interior aesthetic terminal points strictly terminating accurately housing flawlessly protected specialized twin-port SC/APC optical wall boxes installed gracefully perfectly natively directly inside occupied housing units.' },
            { icon: '🗄️', title: 'Communal Telecom Racking', text: 'Substantial heavy resilient centralized base staging rack architectures decisively completely securely comprehensively encapsulating effectively isolating safely extremely fragile massively concentrated fusion grouping hubs cleanly intelligently securely preparing flawless subsequent external telecom provider hand-offs.' },
            { icon: '🔥', title: 'Flawless Micro-Fusion', text: 'Unyielding completely rigid aggressively disciplined procedural protocols definitively commanding absolute 100% total mandatory arc welding mechanical splicing actively completely totally comprehensively diagnostically verified systematically completely continuously utilizing profound strict strict OTDR algorithmic testing systems.' },
            { icon: '📐', title: 'ICT Legislation Alignment', text: 'Rigorous absolute legally binding procedural compliance thoroughly completely entirely satisfying matching decisively flawlessly meeting fully deeply strict mandatory Spanish ICT2 modern unified telecommunication infrastructural overarching deployment regulations.' },
            { icon: '🤝', title: 'Community Association Partnerships', text: 'Dedicated fluid deeply integrated operational consultative administrative coordination routinely seamlessly professionally successfully engaging directly continuously alongside highly organized collective building administrative property management board authorities generating deeply accurate broadly acceptable transparent collective financial implementation proposals.' },
        ],
        faq: [
            { q: 'Could you define what FTTH means?', a: 'FTTH (Fiber To The Home) refers to bringing high-speed optical fiber directly from the street into an individual residence or apartment.' },
            { q: 'How much does it cost to outfit a residential building with FTTH?', a: 'A standard 10-apartment building ranges around €2000-4000 depending on floors and endpoints, with racks and fusions included.' },
            { q: 'Can individual residents contract completely different independent operators?', a: 'Yes! The installed core vertical FTTH architecture operates completely neutrally. Any subsequent external telecom provider simply links their street fiber directly into the communal basement rack, immediately actively feeding any specific corresponding contracted apartment instantly.' },
        ],
    },
    {
        slug: 'cableado-estructurado-empresas',
        title: 'Structured Cabling for Businesses Barcelona | CableCore',
        h1: 'Structured cabling for businesses in Barcelona',
        h2s: ['Why businesses need structured cabling', 'Our process for business projects', 'Frequently asked questions'],
        intro: 'We design and install structured cabling infrastructure for businesses of all sizes in Barcelona and the metropolitan area. From 5-desk offices to 200+ point corporate buildings. ISO/IEC 11801 compliant, full AS-BUILT documentation, and 5-year extended warranty. Our own certified technicians — no subcontractors.',
        metaDescription: 'Structured cabling for businesses in Barcelona. ISO/IEC 11801, Cat6A/Cat7, rack, patch panel, AS-BUILT documentation. Free quote. ☎ +34 605 974 605',
        cta: 'Does your business need structured cabling?',
        features: [
            { icon: '🏢', title: 'Projects from 5 to 200+ workstations', text: 'We scale every project to the real size of your business: from small offices to large corporate headquarters with hundreds of network points.' },
            { icon: '📐', title: 'Technical project included', text: 'We provide layout plans with cable routes, rack placement, point count, and cable category — at no extra cost.' },
            { icon: '🏗️', title: 'ISO/IEC 11801 standard', text: 'Every installation meets the international structured cabling standard. Categories 6, 6A, and 7 depending on project needs.' },
            { icon: '📊', title: 'Fluke certification', text: 'Every cable pair measured with a Fluke Networks certifier. Written report with results for each point for your IT records.' },
            { icon: '📁', title: 'AS-BUILT documentation', text: 'Final plans with actual cable routes, full labeling, and test results. The documentation your IT department needs to manage the network.' },
            { icon: '🛡️', title: '5-year warranty', text: 'Extended 5-year warranty on materials and labor. If any point fails in that period, we fix it at no cost.' },
        ],
        faq: [
            { q: 'How much does structured cabling cost for a business in Barcelona?', a: 'It depends on the number of workstations. A 10-desk office with rack, patch panel, and testing costs between €2,000 and €3,500. For 20 desks, €3,500–€6,000. For 50+ we provide a custom quote.' },
            { q: 'How long does the installation take?', a: 'A 10–15 desk office requires 2–3 days of installation plus 1 day of testing and documentation. For larger projects we plan in phases to avoid disrupting operations.' },
            { q: 'Can you install outside business hours?', a: 'Yes, we offer night and weekend installations for businesses that cannot stop during the day. No surcharge for overnight work on projects with 15+ points.' },
            { q: 'What cable category do you recommend for a business?', a: 'Cat6A (10 Gbps) is the current standard for new business installations. It is ready for future technologies like Wi-Fi 6E, PoE++, and 10GbE.' },
        ],
    },
    {
        slug: 'instalador-red-barcelona',
        title: 'Network Installer Barcelona | CableCore — Certified Technicians',
        h1: 'Professional network installer in Barcelona',
        h2s: ['Why choose a professional network installer', 'What our service includes', 'Frequently asked questions'],
        intro: 'CableCore is your network installer in Barcelona with over 10 years of experience and 500+ completed projects. We install Ethernet networks, fiber optics, enterprise Wi-Fi, and structured cabling in homes, offices, and industrial warehouses. Certified in-house technicians, quotes within 24 hours, and a 5-year warranty on all work.',
        metaDescription: 'Network installer in Barcelona. 500+ projects. Ethernet, fiber optics, Wi-Fi. Certified in-house technicians. Free quote in 24h. ☎ +34 605 974 605',
        cta: 'Need a network installer in Barcelona?',
        features: [
            { icon: '👨‍🔧', title: 'Certified in-house technicians', text: 'No subcontracting. All work is carried out by CableCore\'s own certified technicians trained in structured cabling and fiber optics.' },
            { icon: '🌐', title: 'All network types', text: 'Ethernet Cat5e/Cat6/Cat6A/Cat7, single-mode and multimode fiber optics, enterprise Wi-Fi, VoIP, CCTV, and home automation.' },
            { icon: '🏠', title: 'Homes and apartments', text: 'Improve home connectivity with Ethernet cable in every room. From €180 for 2 points with decorative conduit.' },
            { icon: '🏢', title: 'Offices and businesses', text: 'Turnkey structured cabling for Barcelona businesses. Technical project, installation, testing, and AS-BUILT documentation.' },
            { icon: '🏭', title: 'Industrial warehouses', text: 'Cat6A and Cat7 installations for industrial environments with electromagnetic interference. IP-rated conduit and certified materials.' },
            { icon: '📊', title: 'Testing and documentation', text: 'We deliver a test report for every installed point. If it fails the test, we fix it. Written 5-year warranty.' },
        ],
        faq: [
            { q: 'How much does a network installer charge in Barcelona?', a: 'A complete Cat6 network point (cable + outlet + testing) starts from €95. A 4-point home network with conduit from €450. A 10-desk office (cabling + rack + patch panel) from €1,800. Ask for a free quote.' },
            { q: 'How long does installation take?', a: 'A 2–4 point home in half a day. 8–10 point installation in 1 day. 15–20 desk office in 2–3 days. We always agree on a specific date.' },
            { q: 'Do you work across all of Barcelona?', a: 'Yes, we cover all Barcelona districts and the entire metropolitan area (Badalona, Hospitalet, Sant Cugat, Sabadell, Terrassa, and more).' },
            { q: 'Do you also install Wi-Fi?', a: 'Yes, we complement Ethernet cabling with professional Wi-Fi access points (Ubiquiti, TP-Link EAP). Cable is the backbone; Wi-Fi covers the mobile zones.' },
        ],
    },
];
