/* ═══════════════════════════════════════════
   SEO Landing Pages Data
   Keyword-targeted pages for Barcelona
   ═══════════════════════════════════════════ */

import { SEOPageConfig } from "./types";

export const SEO_PAGES_ES: SEOPageConfig[] = [
    {
        slug: 'instalacion-cable-red-barcelona',
        title: 'Instalación Cable de Red Barcelona | CableCore',
        h1: 'Instalación profesional de cable de red en Barcelona',
        h2s: ['Proceso de instalación paso a paso', 'Materiales y herramientas profesionales', 'Preguntas frecuentes'],
        intro: 'Instalamos cable de red Ethernet en Barcelona con proceso totalmente controlado: visita técnica, trazado de recorridos, tendido de cable, crimpado RJ45, etiquetado y testeo con certificadora. Cat5e, Cat6, Cat6A y Cat7. Sin sorpresas en el presupuesto.',
        metaDescription: 'Instalación de cable de red en Barcelona. Proceso profesional completo: trazado, tendido, crimpado RJ45 y testeo certificado. Cat5e a Cat7. ☎ +34 605 974 605',
        cta: '¿Necesitas instalar cable de red en Barcelona?',
        features: [
            { icon: '📐', title: 'Visita técnica previa', text: 'Medimos el espacio, planificamos los recorridos y calculamos los metros de cable exactos antes de darte precio.' },
            { icon: '🔧', title: 'Tendido limpio', text: 'Pasamos el cable por canaleta, falso techo o empotrado según el acabado que necesitas. Sin cables a la vista.' },
            { icon: '🔌', title: 'Crimpado RJ45 certificado', text: 'Terminamos cada punto con conectores RJ45 de categoría correcta y roseta de superficie o empotrada.' },
            { icon: '🏷️', title: 'Etiquetado profesional', text: 'Cada cable y roseta etiquetados con código para fácil identificación futura.' },
            { icon: '📊', title: 'Testeo con certificadora', text: 'Comprobamos cada par de cables con analizador profesional: continuidad, mapa de pares, NEXT y pérdida de inserción.' },
            { icon: '📋', title: 'Informe de instalación', text: 'Entregamos documentación con el esquema de la instalación y los resultados del testeo de cada punto.' },
        ],
        faq: [
            { q: '¿Cuánto cuesta instalar cable de red en Barcelona?', a: 'Un punto Cat6 completamente instalado (cable + roseta + comprobación) cuesta desde 95€. El precio final depende del número de puntos, metros de cable y tipo de acabado (canaleta o empotrado). Pide presupuesto sin compromiso.' },
            { q: '¿Cuánto tarda la instalación?', a: 'Una instalación doméstica de 4-8 puntos se realiza en 1 día laborable. Proyectos empresariales de 20-30 puntos en 2-3 días. Trabajamos con mínimas molestias.' },
            { q: '¿Es mejor canaleta o empotrado?', a: 'La canaleta es más rápida y económica, ideal para instalaciones en locales ya construidos. El empotrado queda invisible pero requiere obra. En reformas recomendamos siempre empotrado.' },
            { q: '¿Qué categoría de cable necesito?', a: 'Cat6 para uso doméstico (1 Gbps). Cat6A para oficinas que necesiten 10 Gbps. Cat7 para entornos industriales o data centers con muchas interferencias.' },
            { q: '¿Necesito cortar el suministro durante la instalación?', a: 'No. La instalación de cable de red no requiere cortar la electricidad. Trabajamos en paralelo a la actividad del local u hogar. Solo interrumpimos brevemente el switch si ya existe red, para conectar los nuevos puntos.' },
            { q: '¿Ofrecéis garantía en la instalación?', a: 'Sí. Todas nuestras instalaciones tienen 5 años de garantía en materiales y mano de obra. Si un punto falla en ese periodo, lo reparamos sin coste.' },
            { q: '¿Podéis instalar cable de red en un piso de alquiler?', a: 'Sí, usando canaleta adhesiva que no daña paredes ni requiere permiso del propietario. Al finalizar el contrato, la canaleta se retira sin dejar rastro.' },
        ],
    },
    {
        slug: 'cableado-estructurado-barcelona',
        title: 'Cableado Estructurado Barcelona | CableCore',
        h1: 'Cableado estructurado profesional en Barcelona',
        h2s: ['¿Qué incluye un proyecto de cableado estructurado?', 'Normativa y estándares', 'Preguntas frecuentes'],
        intro: 'Diseño e instalación de infraestructuras de cableado estructurado para empresas en Barcelona. Cumplimos la normativa ISO/IEC 11801 y ANSI/TIA-568. Entregamos proyecto técnico completo, etiquetado y documentación AS-BUILT. Garantía extendida de 5 años en materiales y mano de obra.',
        metaDescription: 'Cableado estructurado Barcelona. Diseño bajo norma ISO/IEC 11801, instalación, testeo y documentación AS-BUILT para empresas. ☎ +34 605 974 605',
        cta: '¿Necesitas cableado estructurado en Barcelona?',
        features: [
            { icon: '📐', title: 'Proyecto técnico', text: 'Elaboramos un proyecto con planos de distribución, recorridos de cable, ubicación de racks y número de puntos.' },
            { icon: '🏗️', title: 'Normativa ISO/IEC 11801', text: 'Diseñamos según los estándares internacionales de cableado estructurado para categorías 6, 6A y 7.' },
            { icon: '📈', title: 'Red escalable', text: 'Planificamos la instalación para que puedas ampliar puestos sin rehacer el cableado principal.' },
            { icon: '🗄️', title: 'Rack y patch panel', text: 'Instalamos armario de telecomunicaciones con patch panel etiquetado, organizador de cables y alimentación rack.' },
            { icon: '📊', title: 'Testeo y certificación', text: 'Medimos cada par con certificadora Fluke para verificar que cumple la categoría contratada. Informe por escrito.' },
            { icon: '📁', title: 'Documentación AS-BUILT', text: 'Entregamos planos finales con los recorridos reales, etiquetado completo y resultados de testeo de todos los puntos.' },
        ],
        faq: [
            { q: '¿Qué es el cableado estructurado?', a: 'Es una infraestructura de cableado organizada y estandarizada que permite transmitir voz, datos y vídeo dentro de un edificio. La clave es que sigue una normativa (ISO/IEC 11801) que garantiza el rendimiento y la compatibilidad a largo plazo.' },
            { q: '¿Cuánto cuesta el cableado estructurado en Barcelona?', a: 'Un proyecto completo para una oficina de 10 puestos está entre 2.000€ y 3.500€ (rack + patch panel + 10 puntos Cat6A + testeo + documentación). Para 20 puestos entre 3.500€ y 6.000€. El precio varía según categoría de cable y complejidad del espacio.' },
            { q: '¿Cuánto se tarda en instalar cableado estructurado?', a: 'Una oficina de 10-15 puestos requiere 2-3 días de instalación más 1 día de testeo y documentación. Proyectos más grandes se planifican por fases para no interrumpir la actividad.' },
            { q: '¿Se puede hacer en un local ya construido?', a: 'Sí, trabajamos con canaleta cable, falso techo técnico y empotrado para adaptar la instalación a cualquier espacio. Previo a la instalación hacemos una visita técnica para evaluar las posibilidades.' },
            { q: '¿Qué diferencia hay entre Cat6 y Cat6A en cableado estructurado?', a: 'Cat6A soporta 10 Gbps hasta 100m y es el estándar recomendado para nuevas instalaciones empresariales. Cat6 soporta 1 Gbps y es suficiente para oficinas pequeñas con menos de 20 puestos.' },
        ],
    },
    {
        slug: 'instalacion-cat6-barcelona',
        title: 'Instalación Cat6 Barcelona | CableCore',
        h1: 'Instalación de cable Cat6 en Barcelona',
        h2s: ['Ventajas del Cat6', 'Proceso de instalación', 'Preguntas frecuentes'],
        intro: 'Instalación profesional de cableado Cat6 en Barcelona. Velocidad hasta 1 Gbps, ideal para hogares y oficinas. Presupuesto gratis y sin compromiso.',
        metaDescription: 'Instalación Cat6 en Barcelona. Cable Ethernet 1Gbps para hogar y oficina. Instalador profesional. Presupuesto gratis. ☎ +34 605 974 605',
        cta: '¿Necesitas Cat6 en Barcelona?',
        features: [
            { icon: '⚡', title: 'Hasta 1 Gbps', text: 'Velocidad sobrada para navegación, streaming 4K y trabajo remoto.' },
            { icon: '💰', title: 'Mejor relación calidad-precio', text: 'Cable Cat6 al mejor precio con instalación profesional incluida.' },
            { icon: '🏠', title: 'Ideal para hogar', text: 'Perfecto para domicilios que quieren conexión estable y rápida.' },
            { icon: '📡', title: 'Compatible WiFi 6', text: 'Base perfecta para routers WiFi 6 y puntos de acceso.' },
            { icon: '🔌', title: 'RJ45 testeo', text: 'Todos los puntos verificados y testeados por nuestros técnicos.' },
            { icon: '🛠️', title: 'Instalación limpia', text: 'Canaleta, falso techo o empotrado según tu preferencia.' },
        ],
        faq: [
            { q: '¿Cuál es la diferencia entre Cat5e y Cat6?', a: 'Cat6 soporta velocidades de hasta 1 Gbps a 100m vs 100 Mbps del Cat5e, con mejor blindaje contra interferencias.' },
            { q: '¿Cat6 es suficiente para mi oficina?', a: 'Para oficinas pequeñas con hasta 10 empleados, Cat6 es una excelente opción. Si necesitas más de 1 Gbps, considera Cat6A.' },
        ],
    },
    {
        slug: 'instalacion-cat6a-barcelona',
        title: 'Instalación Cat6A Barcelona | CableCore',
        h1: 'Instalación de cable Cat6A en Barcelona',
        h2s: ['Ventajas del Cat6A', 'Proceso de instalación', 'Preguntas frecuentes'],
        intro: 'Instalación profesional de cableado Cat6A en Barcelona. Velocidad de 10 Gbps, apantallado, ideal para empresas que exigen alto rendimiento de red.',
        metaDescription: 'Instalación Cat6A en Barcelona. Cable 10Gbps apantallado para empresas. Instalador profesional. ☎ +34 605 974 605',
        cta: '¿Necesitas Cat6A para tu empresa?',
        features: [
            { icon: '🚀', title: 'Hasta 10 Gbps', text: '10 veces más rápido que Cat6 estándar para grandes transferencias de datos.' },
            { icon: '🛡️', title: 'Apantallado (FTP)', text: 'Mayor protección contra interferencias electromagnéticas.' },
            { icon: '🏢', title: 'Ideal para empresas', text: 'La elección preferida para oficinas medianas y grandes.' },
            { icon: '📊', title: 'Futuro-proof', text: 'Preparado para tecnologías como WiFi 6E, PoE++ y 10GbE.' },
            { icon: '🏥', title: 'Sectores exigentes', text: 'Perfecto para clínicas, estudios de diseño y empresas tech.' },
            { icon: '✅', title: 'Testeo', text: 'Comprobamos cada punto hasta 500 MHz con equipos profesionales.' },
        ],
        faq: [
            { q: '¿Merece la pena Cat6A frente a Cat6?', a: 'Si tu empresa maneja grandes volúmenes de datos o planeas crecer en los próximos 5-10 años, Cat6A es una inversión inteligente.' },
            { q: '¿Cat6A funciona con mis equipos actuales?', a: 'Sí, Cat6A es retrocompatible con Cat6 y Cat5e. Puedes actualizarte sin cambiar switches ni routers.' },
        ],
    },
    {
        slug: 'instalacion-cat7-barcelona',
        title: 'Instalación Cat7 Barcelona | CableCore',
        h1: 'Instalación de cable Cat7 en Barcelona',
        h2s: ['Ventajas del Cat7', 'Proceso de instalación', 'Preguntas frecuentes'],
        intro: 'Instalación de cableado Cat7 en Barcelona para los entornos más exigentes. Blindaje S/FTP, hasta 10 Gbps y frecuencia de 600 MHz.',
        metaDescription: 'Instalación Cat7 en Barcelona. Cable S/FTP 10Gbps 600MHz para entornos industriales y data centers. ☎ +34 605 974 605',
        cta: '¿Necesitas Cat7 para tu proyecto?',
        features: [
            { icon: '⚡', title: '10 Gbps / 600 MHz', text: 'Máximo rendimiento para entornos industriales y data centers.' },
            { icon: '🛡️', title: 'Doble blindaje S/FTP', text: 'Cada par blindado individualmente más blindaje global.' },
            { icon: '🏭', title: 'Industrial', text: 'Ideal para fábricas, naves y entornos con interferencias electromagnéticas.' },
            { icon: '📡', title: 'PoE++', text: 'Soporta Power over Ethernet para cámaras, APs y dispositivos IoT.' },
            { icon: '🔒', title: 'Máxima fiabilidad', text: 'Conectores GG45 o TERA para conexiones a prueba de errores.' },
            { icon: '📐', title: 'Normativa completa', text: 'Cumple con las normas más estrictas: ISO/IEC 11801 Class F.' },
        ],
        faq: [
            { q: '¿Cuándo necesito Cat7?', a: 'Cuando el entorno tiene muchas interferencias electromagnéticas (fábricas, CPDs) o necesitas la máxima calidad de señal.' },
            { q: '¿Es compatible Cat7 con mis equipos?', a: 'Sí, Cat7 con conectores RJ45 es compatible con todo el equipo estándar.' },
        ],
    },
    {
        slug: 'instalador-rj45-barcelona',
        title: 'Instalador RJ45 Barcelona | CableCore',
        h1: 'Instalador de conectores RJ45 en Barcelona',
        h2s: ['Servicio profesional RJ45', 'Proceso', 'FAQ'],
        intro: 'Instalación y comprobación de conectores RJ45 en Barcelona. Crimpado profesional, colocación de rosetas y testeo de cada punto de red.',
        metaDescription: 'Instalador RJ45 en Barcelona. Crimpado profesional, rosetas y testeo. Servicio rápido y garantizado. ☎ +34 605 974 605',
        cta: '¿Necesitas un instalador RJ45?',
        features: [
            { icon: '🔌', title: 'Crimpado profesional', text: 'Terminación de conectores RJ45 con herramientas de precisión.' },
            { icon: '🔍', title: 'Testeo individual', text: 'Cada conector se verifica con tester profesional.' },
            { icon: '📐', title: 'Cat5e a Cat7', text: 'Trabajamos con todas las categorías de cable Ethernet.' },
            { icon: '🏠', title: 'Domicilio y empresa', text: 'Servicio a domicilio para hogares, oficinas y naves.' },
            { icon: '⚡', title: 'Servicio rápido', text: 'Instalación de puntos RJ45 en el día en Barcelona.' },
            { icon: '✅', title: 'Garantía', text: 'Garantía en cada punto instalado y comprobado.' },
        ],
        faq: [
            { q: '¿Cuánto cuesta instalar un punto RJ45?', a: 'Un punto RJ45 instalado y comprobado cuesta desde 15€ (solo conector) hasta 45-85€ (punto completo con cable y roseta).' },
        ],
    },
    {
        slug: 'instalacion-rack-red-barcelona',
        title: 'Instalación Rack de Red Barcelona | CableCore',
        h1: 'Instalación de rack de red en Barcelona',
        h2s: ['Tipos de rack que instalamos', 'Proceso', 'FAQ'],
        intro: 'Instalación profesional de racks de red en Barcelona. Racks de pared, de suelo y armarios de telecomunicaciones con patch panel y organización de cableado.',
        metaDescription: 'Instalación de rack de red en Barcelona. Racks de pared y suelo, patch panel, organización de cableado. ☎ +34 605 974 605',
        cta: '¿Necesitas instalar un rack de red?',
        features: [
            { icon: '🗄️', title: 'Rack de pared', text: 'Desde 6U hasta 18U para oficinas y PYMES. Instalación limpia en pared.' },
            { icon: '🏗️', title: 'Rack de suelo', text: 'Desde 22U hasta 42U para grandes instalaciones y CPDs.' },
            { icon: '🔗', title: 'Patch panel', text: 'Organización de conexiones con patch panel Cat6/Cat6A/Cat7.' },
            { icon: '🔄', title: 'Organización', text: 'Pasacables, paneles ciegos y gestión de cables profesional.' },
            { icon: '🔌', title: 'Alimentación', text: 'Regletas rack con protección contra sobretensiones.' },
            { icon: '❄️', title: 'Ventilación', text: 'Bandejas de ventilación y termos para racks cerrados.' },
        ],
        faq: [
            { q: '¿Qué tamaño de rack necesito?', a: 'Para una oficina pequeña, un rack de pared 12U es suficiente. Para más de 20 puntos, recomendamos rack de suelo desde 22U.' },
            { q: '¿Incluye el patch panel?', a: 'Ofrecemos instalación de rack con y sin patch panel. El rack con patch panel integrado incluye organización completa.' },
        ],
    },
    {
        slug: 'instalacion-red-oficina-barcelona',
        title: 'Instalación Red Oficina Barcelona | CableCore',
        h1: 'Instalación de red para oficinas en Barcelona',
        h2s: ['Soluciones para oficinas', 'Proceso', 'FAQ'],
        intro: 'Instalación completa de red para oficinas en Barcelona. Diseño, cableado estructurado, rack, WiFi empresarial y configuración de red. Todo llave en mano.',
        metaDescription: 'Instalación de red para oficinas en Barcelona. Cableado + rack + WiFi + configuración. Llave en mano. ☎ +34 605 974 605',
        cta: '¿Necesitas montar la red de tu oficina?',
        features: [
            { icon: '🏢', title: 'Solución completa', text: 'Diseño, cableado, rack, WiFi y configuración en un solo servicio.' },
            { icon: '📐', title: 'Diseño personalizado', text: 'Analizamos tu oficina para optimizar la distribución de puntos de red.' },
            { icon: '📡', title: 'WiFi empresarial', text: 'Puntos de acceso profesionales para cobertura total sin zonas muertas.' },
            { icon: '⚙️', title: 'Configuración', text: 'Configuración de switches, VLANs y segmentación de red.' },
            { icon: '🔒', title: 'Seguridad', text: 'Red segmentada con acceso seguro para empleados e invitados.' },
            { icon: '📋', title: 'Documentación', text: 'Planos de red, etiquetado y documentación técnica completa.' },
        ],
        faq: [
            { q: '¿Cuánto cuesta montar la red de una oficina?', a: 'Depende del tamaño: una oficina de 10 puestos desde 1.500€, de 20 puestos desde 3.000€, y de 50 puestos desde 6.000€.' },
            { q: '¿Podéis trabajar fuera de horario?', a: 'Sí, instalamos en horario nocturno o fines de semana para no interrumpir tu actividad.' },
        ],
    },
    {
        slug: 'instalacion-red-casa-barcelona',
        title: 'Instalación Red Casa Barcelona | CableCore',
        h1: 'Instalación de red doméstica en Barcelona',
        h2s: ['Ventajas del cable en casa', 'Proceso', 'FAQ'],
        intro: 'Instalación de red Ethernet en casa en Barcelona. Mejora tu WiFi, elimina zonas muertas y disfruta de conexión estable en cada habitación.',
        metaDescription: 'Instalación de red en casa en Barcelona. Cable Ethernet + WiFi profesional. Elimina zonas muertas. ☎ +34 605 974 605',
        cta: '¿Quieres mejorar la red de tu casa?',
        features: [
            { icon: '🏠', title: 'Red en toda la casa', text: 'Puntos Ethernet en salón, despacho, dormitorios y zonas comunes.' },
            { icon: '📡', title: 'WiFi sin zonas muertas', text: 'Puntos de acceso conectados por cable para WiFi perfecto en toda la vivienda.' },
            { icon: '🎮', title: 'Gaming y streaming', text: 'Latencia mínima para juegos online y streaming 4K sin buffering.' },
            { icon: '💼', title: 'Teletrabajo', text: 'Conexión estable para videoconferencias y trabajo remoto sin cortes.' },
            { icon: '🔧', title: 'Instalación discreta', text: 'Canaleta decorativa o empotrado para una instalación invisible.' },
            { icon: '💰', title: 'Precio competitivo', text: 'Desde 180€ para 2 puntos de red y desde 350€ para 4 puntos.' },
        ],
        faq: [
            { q: '¿Se puede instalar red Ethernet en un piso ya construido?', a: 'Sí, usamos canaleta decorativa o aprovechamos tubos existentes. En reformas, podemos empotrar el cable.' },
            { q: '¿Cuántos puntos de red necesito en casa?', a: 'Recomendamos mínimo 2 puntos (salón y despacho). Ideal: 4 puntos (añadiendo dormitorios).' },
        ],
    },
    {
        slug: 'instalacion-patch-panel-barcelona',
        title: 'Instalación Patch Panel Barcelona | CableCore',
        h1: 'Instalación de patch panel en Barcelona',
        h2s: ['Por qué necesitas un patch panel', 'Tipos y configuraciones', 'Preguntas frecuentes'],
        intro: 'Instalación y configuración de patch panels en Barcelona para empresas que necesitan gestionar su red de forma profesional. Reducimos el tiempo de reconfiguración de horas a minutos y evitamos errores en la sala de servidores. Panel Cat6, Cat6A o Cat7 de 12, 24 y 48 puertos.',
        metaDescription: 'Instalación patch panel Barcelona. Organización centralizada de red Cat6/Cat6A/Cat7, 12-48 puertos. Etiquetado y testeo incluidos. ☎ +34 605 974 605',
        cta: '¿Necesitas organizar tu sala de servidores?',
        features: [
            { icon: '🔗', title: 'Gestión centralizada', text: 'Todos los cables del edificio terminan en el patch panel. Cambios de configuración en segundos con un latiguillo.' },
            { icon: '🔄', title: 'Reconfiguración sin obra', text: 'Cambiar qué puesto se conecta a qué switch sin tocar el cableado permanente de paredes y techos.' },
            { icon: '📐', title: '12, 24 o 48 puertos', text: 'Patch panels Cat6 y Cat6A de 12, 24 y 48 puertos para adaptarse al tamaño de tu red.' },
            { icon: '🏷️', title: 'Sistema de etiquetado', text: 'Etiquetamos cada puerto con código de color y número para localizar cualquier punto en segundos.' },
            { icon: '🗄️', title: 'Integración con rack', text: 'Montaje en rack estándar 19" con organizador de latiguillos para un acabado impecable.' },
            { icon: '✅', title: 'Testeo puerto a puerto', text: 'Verificamos cada terminación IDC con tester profesional antes de la entrega.' },
        ],
        faq: [
            { q: '¿Qué es un patch panel y para qué sirve?', a: 'Un patch panel es un módulo de conexiones donde terminan todos los cables del edificio. Permite conectar cualquier punto de red a cualquier puerto del switch usando latiguillos cortos, sin tocar el cableado permanente.' },
            { q: '¿Es imprescindible el patch panel?', a: 'Para instalaciones de más de 8-10 puntos sí es muy recomendable. Sin patch panel, los cables van directamente al switch y cualquier cambio requiere mover cables del techo o paredes.' },
            { q: '¿Cuánto cuesta instalar un patch panel en Barcelona?', a: 'Un patch panel de 24 puertos instalado y etiquetado cuesta desde 180€ (sin rack). Con rack de pared 12U incluye desde 350€. Pide presupuesto según tus necesidades.' },
            { q: '¿Puedo añadir un patch panel a una instalación existente?', a: 'Sí, siempre que los cables existentes lleguen al punto donde instalar el rack. Si los cables ya están en un armario, añadir el patch panel es una instalación de medio día.' },
        ],
    },

    /* ═══════════════════════════════════════════
       Location-Targeted Pages
       ═══════════════════════════════════════════ */

    {
        slug: 'instalacion-red-barcelona',
        title: 'Instalación de Red en Barcelona | CableCore — Expertos en Redes',
        h1: 'Instalación de red en Barcelona',
        h2s: ['Todos nuestros servicios de red en Barcelona', 'Zonas y barrios que cubrimos', 'Preguntas frecuentes'],
        intro: 'CableCore es tu empresa de instalación de redes en Barcelona con sede en Badalona. Más de 500 instalaciones completadas en Barcelona ciudad y área metropolitana. Cableado estructurado Cat6/Cat6A/Cat7, fibra óptica, racks, WiFi empresarial y redes domésticas. Técnicos propios, sin subcontratas. Presupuesto en 24h.',
        metaDescription: 'Instalación de red en Barcelona. +500 proyectos completados. Cableado Cat6/Cat6A/Cat7, fibra óptica, racks y WiFi. Técnicos propios. Presupuesto gratis ☎ +34 605 974 605',
        cta: '¿Necesitas instalar red en Barcelona?',
        features: [
            { icon: '🌐', title: 'Servicio integral de red', text: 'Cableado Cat6/Cat6A/Cat7, fibra óptica, racks, patch panels, WiFi empresarial y configuración de switches. Todo en una empresa.' },
            { icon: '🏢', title: 'Empresas y oficinas', text: 'Redes llave en mano para oficinas en el 22@, Diagonal, Eixample y Zona Franca. Diseño, instalación y documentación.' },
            { icon: '🏠', title: 'Hogares y pisos', text: 'Red Ethernet para teletrabajo, gaming y streaming en pisos del Gràcia, Sarrià, Les Corts y Sant Andreu.' },
            { icon: '🏭', title: 'Naves industriales', text: 'Cableado industrial resistente para empresas en Zona Franca, Polígon Pratenc, Polígon Mas Blau y zonas industriales de Barcelona.' },
            { icon: '📍', title: 'Toda el área metropolitana', text: 'Cubrimos Barcelona ciudad, Badalona (sede central), L\'Hospitalet, Cornellà, Sant Cugat, Sabadell, Terrassa y toda el área metropolitana.' },
            { icon: '✅', title: 'Garantía 5 años', text: 'Todas las instalaciones con testeo profesional, documentación y garantía de 5 años en materiales y mano de obra.' },
        ],
        faq: [
            { q: '¿Cuánto cuesta instalar red en Barcelona?', a: 'Punto Cat6 instalado desde 95€. Oficina de 10 puestos (cableado + rack + patch panel) desde 1.800€. Instalación doméstica de 4 puntos desde 450€. Pide presupuesto gratis sin compromiso.' },
            { q: '¿Cuánto tarda una instalación de red en Barcelona?', a: 'Un hogar de 4-8 puntos en 1 día. Oficina de 15-20 puntos en 2-3 días. Proyecto industrial de 50+ puntos en 1-2 semanas. Trabajamos fines de semana para no parar tu negocio.' },
            { q: '¿Trabajáis en toda Barcelona ciudad?', a: 'Sí, cubrimos todos los distritos: Eixample, Gràcia, Sant Martí (22@), Sants-Montjuïc, Zona Franca, Horta-Guinardó, Nou Barris, Sant Andreu, Sarrià-Sant Gervasi y Les Corts.' },
            { q: '¿Usáis subcontratas?', a: 'No. Todos los trabajos los realiza personal propio de CableCore. Sin intermediarios, sin sorpresas. El técnico que hace la visita técnica es el mismo que realiza la instalación.' },
            { q: '¿Podéis instalar red WiFi además del cableado?', a: 'Sí. Complementamos el cableado Ethernet con puntos de acceso WiFi empresarial (Ubiquiti, TP-Link EAP) para cobertura total. El cable es la columna vertebral y el WiFi complementa las zonas móviles.' },
            { q: '¿Sois empresa local o subcontratas el trabajo?', a: 'Somos empresa local con sede en Badalona. No subcontratamos. Los técnicos que hacen la visita son los mismos que instalan, lo que garantiza continuidad y responsabilidad.' },
        ],
    },

    {
        slug: 'instalacion-red-hospitalet',
        title: "Instalación Red L'Hospitalet de Llobregat | CableCore",
        h1: "Instalación de red en L'Hospitalet de Llobregat",
        h2s: ["Servicios de red en L'Hospitalet", "Zonas que cubrimos en L'Hospitalet", 'Preguntas frecuentes'],
        intro: "Instalación de redes en L'Hospitalet de Llobregat, la segunda ciudad más poblada de Cataluña. Cubrimos todas las zonas empresariales de L'Hospitalet: Gran Via, Fira de Barcelona, Zona Franca y el polígono industrial de la Torrassa. Cableado Cat6/Cat6A para oficinas, locales comerciales y viviendas. Presupuesto en el día.",
        metaDescription: "Instalación de red en L'Hospitalet de Llobregat. Cobertura en Gran Via, Fira, Zona Franca y Torrassa. Cat6/Cat6A/Cat7. Presupuesto gratis. ☎ +34 605 974 605",
        cta: "¿Necesitas instalación de red en L'Hospitalet?",
        features: [
            { icon: '🏢', title: "Gran Via y Fira de Barcelona", text: "Instalamos redes en las torres de oficinas de Gran Via y en los recintos y hoteles de la Fira de Barcelona en L'Hospitalet." },
            { icon: '🏭', title: 'Zona Franca y polígonos', text: "Cableado industrial para naves y almacenes en la Zona Franca y el polígono industrial de la Torrassa, frecuentemente visitado desde L'Hospitalet." },
            { icon: '🏠', title: "Barrios residenciales", text: "Red Ethernet en pisos de Collblanc, La Torrassa, Santa Eulàlia, Les Planes y el Centre de L'Hospitalet para teletrabajo y streaming." },
            { icon: '🛍️', title: 'Locales comerciales', text: "Cableado para tiendas, clínicas y consultorios en el eje comercial de L'Hospitalet y el centro comercial L'Illa Diagonal." },
            { icon: '⚡', title: 'Respuesta rápida', text: "Desde Badalona llegamos a L'Hospitalet en menos de 30 minutos. Visitas técnicas el mismo día si hay disponibilidad." },
            { icon: '📋', title: 'Presupuesto gratis', text: "Visita técnica en L'Hospitalet sin coste. Presupuesto detallado en 24 horas." },
        ],
        faq: [
            { q: "¿Cuánto cuesta instalar red en L'Hospitalet?", a: "Aplicamos los mismos precios que en Barcelona ciudad. Un punto Cat6 instalado desde 95€, sin recargo por desplazamiento a L'Hospitalet." },
            { q: "¿Instaláis en las oficinas de Gran Via L'Hospitalet?", a: "Sí, tenemos experiencia en los edificios de oficinas del área de Gran Via, incluyendo torres y plantas diáfanas. Trabajamos fuera de horario laboral si es necesario." },
            { q: "¿Podéis instalar red en un piso en La Torrassa o Collblanc?", a: "Sí, cubrimos todos los barrios de L'Hospitalet. Para pisos usamos canaleta decorativa o aprovechamos la canalización existente para no hacer obra." },
            { q: "¿Cuánto tardáis en llegar a L'Hospitalet?", a: "Nuestra sede está en Badalona, pero L'Hospitalet está a menos de 30 minutos. Podemos hacer visita técnica el mismo día si contactas antes de las 14h." },
        ],
    },
    {
        slug: 'instalacion-red-badalona',
        title: 'Instalación Red Badalona | CableCore — Tu Empresa Local',
        h1: 'Instalación de red en Badalona',
        h2s: ['CableCore: empresa local de Badalona', 'Barrios y zonas que cubrimos', 'Preguntas frecuentes'],
        intro: 'CableCore tiene su sede en Carrer Vitor Balaguer 33, Badalona. Somos tu empresa de instalación de redes en Badalona: conocemos la ciudad, sus polígonos industriales (Badalona Sud, Mas Rampinyo) y sus barrios. Tiempo de respuesta mínimo — llegamos a cualquier punto de Badalona en menos de 20 minutos.',
        metaDescription: 'Instalación de red en Badalona. Empresa local con sede en Badalona. Polígonos, oficinas, hogares. Respuesta en el día. Presupuesto gratis. ☎ +34 605 974 605',
        cta: '¿Necesitas red en Badalona?',
        features: [
            { icon: '📍', title: 'Sede en Badalona', text: 'Nuestra oficina está en Carrer Vitor Balaguer 33, Badalona. Somos tu instalador de red local, no una empresa de Barcelona que viene a Badalona.' },
            { icon: '🏭', title: 'Polígonos industriales', text: 'Experiencia en los polígonos de Badalona Sud, Mas Rampinyo, Montigalà y las naves junto a la C-31.' },
            { icon: '🏠', title: 'Todos los barrios', text: 'Instalamos en el Centre, Llefià, La Salut, Gorg, Sant Roc, Artigues, Bufalà, Sistrells y todas las zonas residenciales de Badalona.' },
            { icon: '🏢', title: 'Oficinas y comercios', text: 'Cableado para despachos, clínicas, academias y locales comerciales en el eje de la Av. Martí Pujol y el Mercat Municipal.' },
            { icon: '⚡', title: 'Respuesta en menos de 20 min', text: 'Al estar en Badalona, podemos hacer visita técnica urgente con tiempo de llegada inferior a 20 minutos en la mayoría de casos.' },
            { icon: '🛡️', title: 'Garantía y confianza local', text: 'Empresa conocida en Badalona con más de 10 años de actividad. Garantía 5 años en todas las instalaciones.' },
        ],
        faq: [
            { q: '¿Dónde está vuestra oficina en Badalona?', a: 'Estamos en Carrer Vitor Balaguer 33, 08914 Badalona. Puedes venir a visitarnos o llamar al +34 605 974 605 para concertar una visita técnica.' },
            { q: '¿Cubrís todos los barrios de Badalona?', a: 'Sí, cubrimos toda Badalona: Centre, Llefià, La Salut, Gorg, Sant Roc, Artigues, Bufalà, Sistrells, Pomar, Montigalà y el área industrial.' },
            { q: '¿Hacéis instalaciones en los polígonos de Badalona?', a: 'Sí, tenemos amplia experiencia en los polígonos Badalona Sud y Mas Rampinyo. Instalamos redes industriales Cat6A y Cat7 con canalización IP.' },
            { q: '¿Cuánto cuesta instalar red en Badalona?', a: 'Un punto Cat6 instalado desde 95€, sin ningún recargo por estar en Badalona. Al ser empresa local, nuestros desplazamientos internos son gratuitos.' },
        ],
    },
    {
        slug: 'instalacion-red-sabadell',
        title: 'Instalación Red Sabadell | CableCore',
        h1: 'Instalación de red en Sabadell',
        h2s: ['Servicios en Sabadell y el Vallès Occidental', 'Zonas empresariales y residenciales', 'Preguntas frecuentes'],
        intro: 'Instalación de redes en Sabadell para empresas del Vallès Occidental. Cubrimos los polígonos industriales de Can Roqueta, Can Llong, Polígon Nord y la zona empresarial del Eix Macià. Cableado estructurado Cat6, Cat6A y Cat7 para fábricas, oficinas y hogares en Sabadell.',
        metaDescription: 'Instalación de red en Sabadell. Cobertura en Can Roqueta, Eix Macià, polígonos industriales y zona residencial. Cat6/Cat6A/Cat7. ☎ +34 605 974 605',
        cta: '¿Necesitas instalación de red en Sabadell?',
        features: [
            { icon: '🏭', title: 'Polígonos industriales', text: 'Cableado para naves y empresas en Can Roqueta, Can Llong, Polígon Nord y las zonas industriales del sur de Sabadell.' },
            { icon: '🏢', title: 'Eix Macià y centro', text: 'Redes estructuradas para oficinas y despachos en el Eix Macià, Plaça Catalunya y el centro comercial de Sabadell.' },
            { icon: '🏠', title: 'Barrios residenciales', text: 'Red Ethernet en pisos de Can Puiggener, La Creu Alta, Gràcia, Torre-Romeu y todos los barrios de Sabadell.' },
            { icon: '📡', title: 'WiFi en naves', text: 'Instalación de puntos de acceso industriales con cableado Cat6A para cobertura WiFi total en almacenes y naves.' },
            { icon: '📋', title: 'Presupuesto en 24h', text: 'Contacta hoy y recibe presupuesto detallado con desglose de materiales en 24 horas.' },
            { icon: '✅', title: 'Mismos precios que Barcelona', text: 'No aplicamos recargo por desplazamiento a Sabadell. Los precios son idénticos a Barcelona ciudad.' },
        ],
        faq: [
            { q: '¿Hacéis instalaciones en los polígonos de Sabadell?', a: 'Sí, cubrimos Can Roqueta, Can Llong, Polígon Nord y las zonas industriales de Sabadell. Instalamos Cat7 con canalización IP para entornos con polvo o humedad.' },
            { q: '¿Cuánto tardáis en llegar a Sabadell?', a: 'Desde nuestra sede en Badalona, llegamos a Sabadell en 30-40 minutos por la B-23. Podemos hacer visita técnica en el mismo día si contactas antes del mediodía.' },
            { q: '¿Instaláis en chalets de Sabadell?', a: 'Sí, hacemos instalaciones en viviendas unifamiliares. Usamos canaleta decorativa o empotrado según el tipo de construcción y la preferencia del cliente.' },
        ],
    },
    {
        slug: 'instalacion-red-terrassa',
        title: 'Instalación Red Terrassa | CableCore',
        h1: 'Instalación de red en Terrassa',
        h2s: ['Servicios en Terrassa', 'Zonas industriales y empresariales', 'Preguntas frecuentes'],
        intro: 'Instalación de redes en Terrassa para empresas y hogares del Vallès Occidental. Experiencia en los polígonos industriales de Ca n\'Aurell, Can Parellada y Vallès Parc Empresarial. Cableado Cat6A y Cat7 para el sector textil e industrial de Terrassa, así como instalaciones domésticas en el centro y zona residencial.',
        metaDescription: 'Instalación de red en Terrassa. Polígonos Ca n\'Aurell, Can Parellada, Vallès Parc. Cat6/Cat6A/Cat7 para industria y hogares. ☎ +34 605 974 605',
        cta: '¿Necesitas red en Terrassa?',
        features: [
            { icon: '🏭', title: 'Industria de Terrassa', text: 'Cableado Cat7 blindado para el sector textil, metalúrgico y empresas del polígono Ca n\'Aurell y Can Parellada.' },
            { icon: '🏢', title: 'Vallès Parc Empresarial', text: 'Redes estructuradas para oficinas en el Vallès Parc Empresarial y la zona de negocios del Passeig de les Lletres.' },
            { icon: '🏗️', title: 'Obra nueva y reforma', text: 'Cableado en edificios nuevos con empotrado o adaptación en locales existentes con canaleta.' },
            { icon: '📡', title: 'WiFi empresarial', text: 'Puntos de acceso WiFi 6 con cableado backbone Cat6A para cobertura total sin zonas muertas.' },
            { icon: '🗄️', title: 'Racks y armarios', text: 'Instalación de armarios de telecomunicaciones para empresas de Terrassa con gestión centralizada.' },
            { icon: '📋', title: 'Sin compromiso', text: 'Visita técnica gratuita y presupuesto detallado. Sin coste de desplazamiento a Terrassa.' },
        ],
        faq: [
            { q: '¿Cubrís Terrassa y alrededores?', a: 'Sí, realizamos instalaciones en Terrassa, Rubí, Matadepera, Ullastrell y municipios del Vallès Occidental. Sin recargo por desplazamiento.' },
            { q: '¿Tenéis experiencia en fábricas de Terrassa?', a: 'Sí, hemos instalado redes en naves industriales del sector textil y metalúrgico. Usamos Cat7 S/FTP para entornos con interferencias electromagnéticas.' },
            { q: '¿Qué tipo de cable recomendáis para una oficina en Terrassa?', a: 'Para oficinas en Terrassa recomendamos Cat6A (10 Gbps). Es el estándar actual para nuevas instalaciones empresariales y la mejor inversión a medio plazo.' },
        ],
    },
    {
        slug: 'instalacion-red-sant-cugat',
        title: 'Instalación Red Sant Cugat del Vallès | CableCore',
        h1: 'Instalación de red en Sant Cugat del Vallès',
        h2s: ['Servicios en Sant Cugat', 'Parques empresariales y urbanizaciones', 'Preguntas frecuentes'],
        intro: 'Instalación de red profesional en Sant Cugat del Vallès para empresas y viviendas de alto standing. Cubrimos el Parc Empresarial Can Sant Joan, el Polígon Industrial Les Planes y las urbanizaciones de Can Baró, Volpelleres y La Floresta. Instalaciones premium con materiales de primera calidad y acabados discretos.',
        metaDescription: 'Instalación de red en Sant Cugat del Vallès. Cobertura en Can Sant Joan, Les Planes y urbanizaciones. Instalaciones premium para hogares y empresas. ☎ +34 605 974 605',
        cta: '¿Necesitas red en Sant Cugat?',
        features: [
            { icon: '🏢', title: 'Parc Empresarial Can Sant Joan', text: 'Cableado estructurado para sedes corporativas y oficinas en el Parc Empresarial Can Sant Joan y el Polígon Les Planes.' },
            { icon: '🏠', title: 'Urbanizaciones exclusivas', text: 'Red Ethernet premium en viviendas de Can Baró, Volpelleres, La Floresta y las urbanizaciones residenciales de Sant Cugat.' },
            { icon: '📐', title: 'Diseño a medida', text: 'Para viviendas grandes de Sant Cugat diseñamos la red optimizando puntos por planta, minimizando el cable visible.' },
            { icon: '🔒', title: 'Redes seguras para empresas', text: 'VLAN, segmentación y acceso WiFi controlado para empresas del parque empresarial. Cumplimiento GDPR.' },
            { icon: '📡', title: 'WiFi mesh para chalets', text: 'Sistemas WiFi mesh con puntos de acceso cableados para cobertura total en chalets de 3 plantas con jardín.' },
            { icon: '✅', title: 'Acabados premium', text: 'Rosetas empotradas, cableado invisible y acabados que respetan la estética de las viviendas de Sant Cugat.' },
        ],
        faq: [
            { q: '¿Hacéis instalaciones en chalets de Sant Cugat?', a: 'Sí, tenemos amplia experiencia en viviendas unifamiliares de Sant Cugat. Instalamos red en todas las plantas con empotrado de cable para un acabado completamente invisible.' },
            { q: '¿Cuánto cuesta cablear un chalet en Sant Cugat?', a: 'Un chalet de 3 plantas con 8-12 puntos de red y WiFi mesh está entre 1.800€ y 3.500€ dependiendo del tamaño y acabado. Incluye todos los puntos empotrados y sistema WiFi profesional.' },
            { q: '¿Instaláis en las empresas del Parc Empresarial Can Sant Joan?', a: 'Sí, tenemos experiencia en el parque empresarial. Instalamos fuera de horario laboral para no interrumpir la actividad y entregamos documentación completa.' },
            { q: '¿Podéis hacer la instalación empotrada sin hacer mucha obra?', a: 'Sí, usamos técnicas de canalización por falso techo técnico o empotrado mínimo por las tabiques. En viviendas de nueva construcción siempre recomendamos empotrado completo.' },
        ],
    },
    {
        slug: 'instalacion-red-cornella',
        title: 'Instalación Red Cornellà de Llobregat | CableCore',
        h1: 'Instalación de red en Cornellà de Llobregat',
        h2s: ['Servicios en Cornellà y el Baix Llobregat', 'Polígonos y zonas empresariales', 'Preguntas frecuentes'],
        intro: 'Instalación de redes en Cornellà de Llobregat y el Baix Llobregat. Cubrimos el Polígon Industrial Gran Via Sud, la Zona Industrial de la Almeda y el Parc Empresarial de Cornellà. También instalamos en los barrios residenciales de Sant Ildefons, Gavarra y Almeda. Empresa de confianza en el Baix Llobregat.',
        metaDescription: 'Instalación de red en Cornellà de Llobregat. Polígon Gran Via Sud, Almeda, Parc Empresarial. Baix Llobregat. Cat6/Cat6A/Cat7. ☎ +34 605 974 605',
        cta: '¿Necesitas red en Cornellà?',
        features: [
            { icon: '🏭', title: 'Polígon Gran Via Sud', text: 'Cableado estructurado para naves y almacenes en el Polígon Industrial Gran Via Sud, el más grande del Baix Llobregat.' },
            { icon: '🏢', title: 'Parc Empresarial de Cornellà', text: 'Redes para oficinas y empresas en el Parc Empresarial de Cornellà y la zona de la Almeda.' },
            { icon: '🏠', title: 'Barrios de Cornellà', text: 'Instalaciones en pisos de Sant Ildefons, Gavarra, Almeda, Sant Joan Espí y el centre de Cornellà.' },
            { icon: '📍', title: 'Todo el Baix Llobregat', text: 'Desde Cornellà cubrimos Esplugues, Sant Joan Despí, Sant Just Desvern, Molins de Rei y municipios del Baix Llobregat.' },
            { icon: '⚡', title: 'Servicio rápido', text: 'Presupuesto en 24h, instalación en la fecha que elijas. Sin recargo por desplazamiento al Baix Llobregat.' },
            { icon: '🛡️', title: 'Garantía 5 años', text: 'Garantía extendida de 5 años en todos los materiales y mano de obra.' },
        ],
        faq: [
            { q: '¿Cubrís Cornellà de Llobregat?', a: 'Sí, cubrimos Cornellà y todos los municipios del Baix Llobregat: Esplugues, Sant Joan Despí, Sant Just, El Prat, Gavà, Viladecans, Castelldefels y más.' },
            { q: '¿Instaláis en los polígonos industriales de Cornellà?', a: 'Sí, tenemos experiencia en el Polígon Gran Via Sud y la zona industrial de la Almeda. Instalamos Cat6A y Cat7 para entornos industriales.' },
            { q: '¿Cuánto cuesta instalar red en Cornellà?', a: 'Aplicamos los mismos precios que en Barcelona ciudad. Punto Cat6 desde 95€ instalado, sin recargo por desplazamiento.' },
        ],
    },
    {
        slug: 'instalacion-red-sant-boi',
        title: 'Instalación Red Sant Boi de Llobregat | CableCore',
        h1: 'Instalación de red en Sant Boi de Llobregat',
        h2s: ['Servicios en Sant Boi', 'Zonas y barrios', 'Preguntas frecuentes'],
        intro: 'Instalación de redes en Sant Boi de Llobregat. Cubrimos el Polígon Industrial Fontsanta, el Parc Industrial de Can Gambús y los barrios residenciales de Marianao, Camps Blancs y Vinyets. Cableado Ethernet para hogares, comercios y empresas en Sant Boi y municipios del Baix Llobregat sur.',
        metaDescription: 'Instalación de red en Sant Boi de Llobregat. Polígon Fontsanta, Can Gambús, Marianao y Camps Blancs. Cat6/Cat6A/Cat7. ☎ +34 605 974 605',
        cta: '¿Necesitas red en Sant Boi?',
        features: [
            { icon: '🏭', title: 'Polígon Fontsanta y Can Gambús', text: 'Cableado industrial para naves y empresas en el Polígon Industrial Fontsanta y el Parc Industrial de Can Gambús.' },
            { icon: '🏠', title: 'Barrios residenciales', text: 'Red Ethernet en pisos de Marianao, Camps Blancs, Vinyets, El Molí y el centro de Sant Boi.' },
            { icon: '🏢', title: 'Negocios locales', text: 'Cableado para clínicas, academias, consultorios y locales comerciales en Sant Boi.' },
            { icon: '📡', title: 'WiFi sin zonas muertas', text: 'Puntos de acceso cableados para eliminar las zonas sin señal en viviendas y locales.' },
            { icon: '📍', title: 'Sur del Baix Llobregat', text: 'Cubrimos Sant Boi, Viladecans, Gavà, Castelldefels y todos los municipios del litoral del Baix Llobregat.' },
            { icon: '✅', title: 'Garantía total', text: 'Cada punto instalado y testado. Garantía de 5 años en materiales y trabajo.' },
        ],
        faq: [
            { q: '¿Instaláis en Sant Boi de Llobregat?', a: 'Sí, cubrimos Sant Boi y toda la zona sur del Baix Llobregat: Viladecans, Gavà, Castelldefels y l\'Aeroport del Prat.' },
            { q: '¿Hacéis instalaciones en los polígonos de Sant Boi?', a: 'Sí, instalamos en el Polígon Fontsanta y Can Gambús. Para entornos industriales recomendamos Cat6A o Cat7 según el nivel de interferencias.' },
            { q: '¿Cuánto cuesta instalar red en Sant Boi?', a: 'Mismos precios que en Barcelona. Punto Cat6 desde 95€. Sin recargo por desplazamiento al Baix Llobregat.' },
        ],
    },
    {
        slug: 'instalacion-red-castelldefels',
        title: 'Instalación Red Castelldefels | CableCore',
        h1: 'Instalación de red en Castelldefels',
        h2s: ['Red para viviendas de Castelldefels', 'WiFi en exteriores y jardines', 'Preguntas frecuentes'],
        intro: 'Instalación de redes en Castelldefels para chalets, apartamentos y empresas de la zona costera del Garraf. Especialistas en viviendas unifamiliares con jardín y segunda residencia: instalamos cable en todas las plantas y puntos de acceso WiFi exterior para terrazas y piscinas. También cubrimos el Parc Empresarial de Castelldefels y la zona de Gavà Mar.',
        metaDescription: 'Instalación de red en Castelldefels. Chalets, segunda residencia, WiFi exterior para jardines. Parc Empresarial Castelldefels. ☎ +34 605 974 605',
        cta: '¿Necesitas red en Castelldefels?',
        features: [
            { icon: '🏖️', title: 'Chalets y segunda residencia', text: 'Especialistas en viviendas de Castelldefels, Gavà Mar y Sitges. Red Ethernet en todas las plantas y WiFi para jardín y piscina.' },
            { icon: '📡', title: 'WiFi exterior profesional', text: 'Puntos de acceso exterior IP65 conectados por cable para cobertura WiFi perfecta en terrazas, jardines y piscinas.' },
            { icon: '🏢', title: 'Parc Empresarial de Castelldefels', text: 'Cableado estructurado para empresas tecnológicas y oficinas en el Parc Empresarial de Castelldefels junto a la B-23.' },
            { icon: '🎮', title: 'Gaming y smart home', text: 'Red de baja latencia para gaming competitivo y soporte técnico para dispositivos domóticos y smart home.' },
            { icon: '🏘️', title: 'Toda la costa del Garraf', text: 'Servicio en Castelldefels, Gavà, Gavà Mar, Sitges, Vilanova i la Geltrú y municipios de la costa del Garraf.' },
            { icon: '🛡️', title: 'Materiales para el exterior', text: 'Cables y conectores certificados para exteriores, resistentes a la humedad y exposición solar del litoral mediterráneo.' },
        ],
        faq: [
            { q: '¿Hacéis instalaciones en chalets de Castelldefels?', a: 'Sí, es uno de nuestros servicios principales en la zona. Instalamos red en todas las plantas del chalet con cable empotrado o canaleta y añadimos WiFi exterior para jardín y terraza.' },
            { q: '¿Podéis instalar WiFi en el jardín o junto a la piscina?', a: 'Sí, instalamos puntos de acceso exterior certificados IP65, resistentes al agua y al sol. Se conectan por cable desde el interior para señal estable en toda la parcela.' },
            { q: '¿Instaláis en segunda residencia?', a: 'Sí, hacemos instalaciones en segunda residencia. Podemos coordinar el acceso con el servicio de limpieza o conserje y enviarte el informe de la instalación por email.' },
            { q: '¿Cuánto cuesta cablear un chalet en Castelldefels?', a: 'Un chalet de 2 plantas con 6-10 puntos de red y WiFi exterior cuesta entre 1.500€ y 2.800€ según el tamaño y acabados. Pide presupuesto sin compromiso.' },
        ],
    },
    {
        slug: 'instalacion-red-mataro',
        title: 'Instalación Red Mataró | CableCore',
        h1: 'Instalación de red en Mataró',
        h2s: ['Servicios en Mataró y el Maresme', 'Zonas industriales y empresariales', 'Preguntas frecuentes'],
        intro: 'Instalación de redes en Mataró para empresas y hogares del Maresme. Cubrimos el Polígon Industrial Pla d\'en Boet, el Parc Empresarial de la Mata y el nou Centre Comercial Mataró Park. Cableado Cat6, Cat6A y Cat7 para la industria mataronina, despachos del centre i viviendas en Els Molins, Cirera i Rocafonda.',
        metaDescription: 'Instalación de red en Mataró. Polígon Pla d\'en Boet, Parc Empresarial La Mata, centre i barris residencials. Cat6/Cat6A/Cat7. ☎ +34 605 974 605',
        cta: '¿Necesitas red en Mataró?',
        features: [
            { icon: '🏭', title: 'Polígon Pla d\'en Boet', text: 'Cableado estructurado para empresas del Polígon Industrial Pla d\'en Boet, el mayor de Mataró, con más de 300 empresas.' },
            { icon: '🏢', title: 'Centre i eix comercial', text: 'Redes para despachos, consultoris i comerços en el centre de Mataró i la zona de la Rambla.' },
            { icon: '🏠', title: 'Barris residencials', text: 'Instal·lació Ethernet en pisos i cases dels barris d\'Els Molins, Cirera, Rocafonda, Vista Alegre i Cerdanyola.' },
            { icon: '🏪', title: 'Mataró Park', text: 'Experiència en locals comercials i oficines del centre comercial Mataró Park i la zona de gran consum.' },
            { icon: '⚡', title: 'Pressupost en 24h', text: 'Responem el pressupost en 24 hores i podem fer la visita tècnica l\'endemà si és necessari.' },
            { icon: '📊', title: 'Testeo professional', text: 'Mesurem cada parell de cables amb analitzador professional. Informe de testeo inclòs.' },
        ],
        faq: [
            { q: '¿Llegáis hasta Mataró?', a: 'Sí, cubrimos toda la comarca del Maresme desde Montgat hasta Mataró y Arenys de Mar. Sin recargo por desplazamiento.' },
            { q: '¿Los precios son iguales que en Barcelona?', a: 'Sí, nuestros precios son los mismos en toda el área metropolitana y el Maresme. Sin recargos por distancia.' },
            { q: '¿Instaláis en los polígonos de Mataró?', a: 'Sí, tenemos experiencia en el Polígon Pla d\'en Boet y el Parc Empresarial La Mata. Instalamos Cat6A para oficinas y Cat7 para naves industriales.' },
        ],
    },
    {
        slug: 'instalacion-red-granollers',
        title: 'Instalación Red Granollers | CableCore',
        h1: 'Instalación de red en Granollers',
        h2s: ['Servicios en Granollers y el Vallès Oriental', 'Polígonos y zonas empresariales', 'Preguntas frecuentes'],
        intro: 'Instalación de redes en Granollers para empresas del Vallès Oriental. Cubrimos el Polígon Industrial Les Franqueses, Can Prat, el Parc Industrial de Granollers y la zona del Mercat Central. Cableado Cat6, Cat6A y Cat7 para la industria del Vallès Oriental, oficinas del centre de Granollers i viviendas en La Garriga, Mollet i Canovelles.',
        metaDescription: 'Instalació de xarxa a Granollers. Polígon Les Franqueses, Can Prat, Parc Industrial. Vallès Oriental. Cat6/Cat6A/Cat7. ☎ +34 605 974 605',
        cta: '¿Necesitas red en Granollers?',
        features: [
            { icon: '🏭', title: 'Polígons del Vallès Oriental', text: 'Cableado estructurado para empresas en el Polígon Les Franqueses, Can Prat i el Parc Industrial de Granollers i Canovelles.' },
            { icon: '🏢', title: 'Centre de Granollers', text: 'Xarxes per a oficines, despatxos i comerços al centre de Granollers i a la zona del Mercat Central.' },
            { icon: '🏠', title: 'Municipis del Vallès Oriental', text: 'Instal·lació Ethernet en vivendes de Granollers, Mollet del Vallès, La Garriga, Parets del Vallès i Cardedeu.' },
            { icon: '📡', title: 'WiFi per a naus', text: 'Punts d\'accés WiFi 6 amb cablejat backbone Cat6A per a cobertura total en magatzems i naus industrials.' },
            { icon: '📋', title: 'Pressupost 24h', text: 'Contacta avui i rep pressupost detallat en 24 hores. Visita tècnica sense compromís a Granollers.' },
            { icon: '✅', title: 'Garantia 5 anys', text: 'Materials de qualitat amb garantia estesa de 5 anys en tots els treballs.' },
        ],
        faq: [
            { q: '¿Hacéis instalaciones en Granollers?', a: 'Sí, cubrimos Granollers y todo el Vallès Oriental: Mollet del Vallès, La Garriga, Parets del Vallès, Cardedeu, Les Franqueses y Aiguafreda.' },
            { q: '¿Instaláis en los polígonos de Granollers?', a: 'Sí, trabajamos en el Polígon Les Franqueses, Can Prat y el Parc Industrial de Granollers. Para naves industriales recomendamos Cat6A o Cat7 según las interferencias.' },
            { q: '¿Los precios son los mismos que en Barcelona?', a: 'Sí, mismos precios en todo el Vallès Oriental. Sin recargo por desplazamiento a Granollers.' },
        ],
    },

    /* ═══════════════════════════════════════════
       FIBRA ÓPTICA — SEO Pages
       ═══════════════════════════════════════════ */

    {
        slug: 'instalacion-fibra-optica-barcelona',
        title: 'Instalación de Fibra Óptica Barcelona | CableCore',
        h1: 'Instalación de fibra óptica en Barcelona',
        h2s: ['Servicios de fibra óptica en Barcelona', 'Equipamiento y tecnología que usamos', 'Preguntas frecuentes'],
        intro: 'Instalación de fibra óptica en Barcelona por técnicos certificados. Realizamos fusiones por arco eléctrico, tendido de fibra monomodo (SM) y multimodo (OM3/OM4), instalación de racks y bandejas de empalme, y testeo OTDR de cada hilo. Especialistas en FTTH para comunidades de vecinos y enlaces de backbone empresarial en Barcelona y área metropolitana.',
        metaDescription: 'Instalación fibra óptica Barcelona. Técnicos certificados: fusión por arco, OTDR, monomodo/multimodo, FTTH edificios. Presupuesto gratis. ☎ +34 605 974 605',
        cta: '¿Necesitas instalar fibra óptica en Barcelona?',
        features: [
            { icon: '🔥', title: 'Fusión por arco eléctrico', text: 'Empalmes con fusionadora Fujikura de última generación. Atenuación típica < 0.02 dB, muy por debajo del máximo admisible.' },
            { icon: '📊', title: 'Testeo OTDR incluido', text: 'Medimos cada fibra con reflectómetro óptico EXFO. Entregamos informe gráfico del trazado y las pérdidas de cada empalme y conector.' },
            { icon: '🔆', title: 'Monomodo y multimodo', text: 'Instalamos fibra SM G.657A (FTTH), SM G.652D (larga distancia), OM3 y OM4 (backbone de edificio).' },
            { icon: '🏢', title: 'FTTH para comunidades', text: 'Instalamos FTTH vertical en edificios de Barcelona: desde el rack del cuarto de telecomunicaciones hasta la roseta SC/APC de cada vivienda.' },
            { icon: '🗄️', title: 'Racks y bandejas', text: 'Instalamos racks de fibra 19", bandejas de empalme 1U, cajas de segregación y cajas murales para organización profesional.' },
            { icon: '⚡', title: 'Urgencias 24/7', text: 'Servicio de reparación de fibra cortada o dañada en Barcelona con respuesta de urgencia. Disponible 24 horas, 7 días a la semana.' },
        ],
        faq: [
            { q: '¿Cuánto cuesta instalar fibra óptica en Barcelona?', a: 'Un punto de fibra instalado con fusión y testeo cuesta desde 55€. Un proyecto FTTH para un edificio de 10 viviendas está entre 2.500€ y 4.500€ con rack, fusiones y rosetas incluidas. Pide presupuesto sin compromiso.' },
            { q: '¿Qué diferencia hay entre fibra monomodo y multimodo?', a: 'La fibra monomodo (SM G.657A) es para distancias medias-largas y es el estándar en FTTH y conexiones entre edificios. La multimodo (OM3/OM4) se usa dentro de edificios para distancias cortas con velocidades de 10-100 Gbps entre switches.' },
            { q: '¿Hacéis fusión de fibra óptica en Barcelona?', a: 'Sí, realizamos fusiones por arco eléctrico con fusionadora profesional Fujikura. Cada fusión se mide con OTDR y se documenta en informe técnico.' },
            { q: '¿Instaláis FTTH en edificios de viviendas de Barcelona?', a: 'Sí, instalamos FTTH vertical en comunidades de vecinos: desde el rack del sótano o cuarto técnico hasta la roseta SC/APC de cada piso. Trabajamos con administradores de fincas.' },
            { q: '¿Tenéis servicio de urgencia para fibra cortada?', a: 'Sí, ofrecemos servicio de urgencia 24/7 para reparación de fibra dañada en Barcelona. Llamada al +34 605 974 605 y enviamos técnico en el menor tiempo posible.' },
        ],
    },
    {
        slug: 'instalacion-fibra-optica-empresas-barcelona',
        title: 'Fibra Óptica para Empresas Barcelona | CableCore',
        h1: 'Instalación de fibra óptica para empresas en Barcelona',
        h2s: ['Soluciones de fibra empresarial', 'Tecnología y equipamiento', 'Preguntas frecuentes'],
        intro: 'Fibra óptica para empresas en Barcelona. Interconexión de sedes, backbone de red, enlaces de alta velocidad y redes de campus con fibra monomodo y multimodo. Comprobación profesional.',
        metaDescription: 'Fibra óptica para empresas en Barcelona. Backbone de red, interconexión de sedes, enlaces 10/40/100 Gbps. Presupuesto gratis. ☎ +34 605 974 605',
        cta: '¿Tu empresa necesita fibra óptica?',
        features: [
            { icon: '🚀', title: 'Alta velocidad', text: 'Enlaces de 10, 40 y 100 Gbps con fibra monomodo y multimodo OM4.' },
            { icon: '🏢', title: 'Interconexión de sedes', text: 'Conectamos oficinas, almacenes y centros de datos con enlaces de fibra dedicados.' },
            { icon: '📡', title: 'Backbone de red', text: 'Fibra óptica como columna vertebral de la red empresarial para máximo rendimiento.' },
            { icon: '🔒', title: 'Seguridad', text: 'La fibra óptica es inmune a interferencias electromagnéticas y difícil de interceptar.' },
            { icon: '📐', title: 'Diseño a medida', text: 'Diseñamos la topología de fibra ideal para tu infraestructura empresarial.' },
            { icon: '✅', title: 'Comprobación completa', text: 'Cada enlace testeado con OTDR e informe técnico detallado.' },
        ],
        faq: [
            { q: '¿Merece la pena fibra óptica para mi empresa?', a: 'Si manejas grandes volúmenes de datos, tienes varias sedes o necesitas enlaces superiores a 1 Gbps, la fibra óptica es la opción más rentable a largo plazo.' },
            { q: '¿Se puede usar fibra óptica junto con cable Ethernet?', a: 'Sí, es lo más habitual. La fibra se usa como backbone entre plantas o edificios, y el Ethernet Cat6A para la distribución a los puestos de trabajo.' },
        ],
    },
    {
        slug: 'cableado-fibra-optica-interior-barcelona',
        title: 'Cableado de Fibra Óptica Interior Barcelona | CableCore',
        h1: 'Cableado de fibra óptica interior en Barcelona',
        h2s: ['Tipos de cableado interior', 'Materiales y acabados', 'Preguntas frecuentes'],
        intro: 'Instalación de cableado de fibra óptica en interiores en Barcelona. Fibra tight-buffer para distribución interior, con canaleta, falso techo o conductos existentes. Acabados profesionales y discretos.',
        metaDescription: 'Cableado de fibra óptica interior en Barcelona. Instalación profesional, acabados discretos. Presupuesto gratis. ☎ +34 605 974 605',
        cta: '¿Necesitas cableado de fibra interior?',
        features: [
            { icon: '🏠', title: 'Fibra interior', text: 'Cable tight-buffer LSZH para instalaciones interiores, conforme a normativa de incendios CPR.' },
            { icon: '📏', title: 'Canaleta decorativa', text: 'Instalación con canaleta para mantener la estética del espacio.' },
            { icon: '🏗️', title: 'Falso techo', text: 'Tendido de fibra por falso techo para instalaciones invisibles.' },
            { icon: '🔧', title: 'Conductos existentes', text: 'Aprovechamos canalizaciones existentes para minimizar obra.' },
            { icon: '🔌', title: 'Rosetas SC/APC', text: 'Puntos de conexión con rosetas ópticas de 2 puertos SC/APC.' },
            { icon: '🗄️', title: 'Cajas murales', text: 'Cajas de terminación de fibra para organización en cada punto.' },
        ],
        faq: [
            { q: '¿Se nota la instalación de fibra interior?', a: 'No si se hace bien. Usamos canaleta mini decorativa o falso techo para que la instalación sea prácticamente invisible.' },
            { q: '¿Qué tipo de cable se usa en interior?', a: 'Usamos cable tight-buffer monomodo con cubierta LSZH (baja emisión de humos), cumpliendo la normativa CPR de seguridad contra incendios.' },
        ],
    },
    {
        slug: 'fusion-fibra-optica-barcelona',
        title: 'Fusión de Fibra Óptica Barcelona | Empalme Profesional | CableCore',
        h1: 'Servicio de fusión de fibra óptica en Barcelona',
        h2s: ['Proceso de fusión', 'Equipamiento profesional', 'Preguntas frecuentes'],
        intro: 'Servicio profesional de fusión (empalme) de fibra óptica en Barcelona. Fusionadora de arco de última generación, pigtails SC/APC, bandejas de empalme y testeo OTDR de cada fusión.',
        metaDescription: 'Fusión de fibra óptica en Barcelona. Empalme por arco profesional, testeo OTDR. Atenuación < 0.05 dB. ☎ +34 605 974 605',
        cta: '¿Necesitas fusionar fibra óptica?',
        features: [
            { icon: '🔥', title: 'Fusión por arco', text: 'Empalme con fusionadora de arco eléctrico de última generación. Atenuación típica < 0.02 dB.' },
            { icon: '📊', title: 'Medición OTDR', text: 'Cada fusión se verifica con reflectómetro óptico para garantizar la calidad del empalme.' },
            { icon: '🔌', title: 'Pigtails SC/APC', text: 'Terminación con pigtails SC/APC de alta calidad para conexión directa a equipos.' },
            { icon: '📋', title: 'Bandejas organizadas', text: 'Cada empalme se protege en bandeja de empalme 1U dentro del rack.' },
            { icon: '🏢', title: 'Edificios FTTH', text: 'Fusiones en cajas de segregación, registros y cuartos de telecomunicaciones.' },
            { icon: '⚡', title: 'Servicio urgente', text: 'Reparación de fibra cortada o dañada con servicio de urgencia 24/7.' },
        ],
        faq: [
            { q: '¿Cuánto cuesta una fusión de fibra óptica?', a: 'El precio por fusión (empalme) es de 15€ por fibra, incluyendo protector de empalme y pigtail SC/APC.' },
            { q: '¿Cuánto tarda una fusión?', a: 'Una fusión individual tarda menos de 2 minutos. Un proyecto de 12-24 fusiones se completa en 2-3 horas incluyendo testeo.' },
            { q: '¿Qué atenuación tiene una fusión?', a: 'Con nuestro equipo profesional, las fusiones tienen una atenuación típica inferior a 0.02 dB, muy por debajo del máximo aceptable de 0.1 dB.' },
        ],
    },
    {
        slug: 'instalacion-ftth-edificios-barcelona',
        title: 'Instalación FTTH Edificios Barcelona | CableCore',
        h1: 'Instalación FTTH para edificios en Barcelona',
        h2s: ['¿Qué es FTTH?', 'Proceso de instalación', 'Preguntas frecuentes'],
        intro: 'Instalación FTTH (Fiber To The Home) en edificios de Barcelona. Cableado vertical de fibra óptica desde el rack comunitario hasta cada vivienda. Rosetas SC/APC de 2 puertos en cada piso. Ideal para comunidades de vecinos.',
        metaDescription: 'Instalación FTTH en edificios de Barcelona. Fibra óptica hasta cada vivienda. Rack, fusión, rosetas SC/APC. ☎ +34 605 974 605',
        cta: '¿Tu edificio necesita FTTH?',
        features: [
            { icon: '🏢', title: 'Cableado vertical', text: 'Fibra monomodo desde el sótano o cuarto de telecomunicaciones hasta cada planta del edificio.' },
            { icon: '🔌', title: 'Roseta en cada vivienda', text: 'Punto de fibra con roseta SC/APC de 2 puertos en el interior de cada vivienda.' },
            { icon: '🗄️', title: 'Rack comunitario', text: 'Rack de fibra centralizado con bandejas de empalme y acopladores para conectar con los operadores.' },
            { icon: '🔥', title: 'Fusión profesional', text: 'Todos los empalmes realizados con fusionadora de arco y verificados con OTDR.' },
            { icon: '📐', title: 'Proyecto ICT', text: 'Cumplimos con la normativa ICT2 para infraestructuras de telecomunicaciones en edificios.' },
            { icon: '🤝', title: 'Comunidades de vecinos', text: 'Trabajamos con administradores de fincas y comunidades para presupuestos colectivos.' },
        ],
        faq: [
            { q: '¿Qué es FTTH?', a: 'FTTH (Fiber To The Home) significa fibra hasta el hogar. Es la instalación de cable de fibra óptica directamente hasta cada vivienda del edificio.' },
            { q: '¿Cuánto cuesta instalar FTTH en un edificio?', a: 'Depende del número de plantas y viviendas. Un edificio de 10 viviendas está en torno a 2.000-4.000€ con rack, fusiones y rosetas incluidas.' },
            { q: '¿Los vecinos pueden contratar operadores diferentes?', a: 'Sí, la instalación FTTH es neutra. Cada operador puede conectar su fibra al rack comunitario y dar servicio a los vecinos que contraten.' },
        ],
    },
];
